### ISSUE TITLE
Question about EVE

### ISSUE THREAD

**Issue by songzh96** [ebaauw/homebridge-rpi#1]
Hi @ebaauw 
Is there a plugin that allows third-party devices to be added to EVE? Add third-party devices to homekit like homebrige.

Best Regards
songzh

**Comment by ebaauw** [comment]
I’m sorry, I don’t understand your question.  A plugin to what?

**Comment by songzh96** [comment]
Can KNX device be added to the EVE App?

**Comment by songzh96** [comment]
I mean I want to add other devices to EVE for control through a plugin similar to homebridge.


Best Regards
songzh

**Comment by ebaauw** [comment]
You need to find (or create) a homebridge plugin for the other device.  Search on the `npm` registry using the `homebridge-plugin` keyword.
