### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by 1rado1** [ebaauw/homebridge-rpi#10]
Hi, can you please help to debug this error:
```
0|homebridge  | [2020-2-21 20:40:50] [Rpi] warning: pi: file handle !== 0
0|homebridge  | [2020-2-21 20:40:50] [Rpi] pi: warning: SyntaxError: Unexpected number in JSON at position 45
0|homebridge  |     at JSON.parse (<anonymous>:null:null)
0|homebridge  |     at RpiAccessory.heartbeat (/usr/lib/node_modules/homebridge-rpi/lib/RpiAccessory.js:76:30)
0|homebridge  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|homebridge  |     at RpiAccessory.<anonymous> (/usr/lib/node_modules/homebridge-rpi/lib/RpiAccessory.js:60:44)
```

**Comment by ebaauw** [comment]
> [Rpi] pi: warning: SyntaxError: Unexpected number in JSON at position 45

This error occurs when homebridge-rpi is trying to parse the output of the `vcgencmd` script.  Could you check the file `/opt/pigpio/vcgencmd.out` on your Pi?

> [Rpi] warning: pi: file handle !== 0

This means the pigpio server has already opened a file, occupying a file handle.  That could be valid if you have another client accessing the pigpiod daemon; it could also indicate some stale handles.  In that case, best restart pigpiod.

**Comment by 1rado1** [comment]
`/opt/pigpio/vcgencmd.out` output
`{"date":"2020-02-22T11:42:39+00:00","load":0,58,"temp":42.9,"freq":600000000,"volt":1.2000,"throttled":"0x0"}`

pigpiod restarted, didn't help

**Comment by ebaauw** [comment]
Oh this is fun: the load average is reported using a decimal `,` instead of a decimal `.`.  This is probably because of system default language setting somewhere.

Could you please try the `vcgencmd` command script from my latest commit?

**Comment by 1rado1** [comment]
Yes, that could be an issue, EN an CZ language is set across the different environments 
```
0|homebrid | [2020-2-22 1:52:27 PM] [Rpi] warning: pi: file handle !== 0
0|homebrid | [2020-2-22 1:52:27 PM] [Rpi] pi: warning: SyntaxError: Unexpected number in JSON at position 45
0|homebrid |     at JSON.parse (<anonymous>:null:null)
0|homebrid |     at RpiAccessory.heartbeat (/usr/lib/node_modules/homebridge-rpi/lib/RpiAccessory.js:76:30)
0|homebrid |     at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by ebaauw** [comment]
Did you replace `/opt/pigpiod/cli/vcgencmd` on the Pi?

**Comment by 1rado1** [comment]
Yes I did according to your last commit and full reboot after that.

**Comment by ebaauw** [comment]
Reboot shouldn't be necessary.  I thought I had tested the new script, but somehow I managed to screw up.  Fixed `vcgencmd` and the README.  Could you please ty again?

**Comment by 1rado1** [comment]
It works, thanks for your support!
