### ISSUE TITLE
warning: Homebridge: 192.168.1.196:8888: cannot connect: ECONNREFUSED

### ISSUE THREAD

**Issue by ambanmba** [ebaauw/homebridge-rpi#101]
Was getting this error. To fix:

sudo nano /lib/systemd/system/pigpiod.service

and then make the ExecStart line look like:
`ExecStart=/usr/bin/pigpiod -l -n 127.0.0.1`

**Comment by ebaauw** [comment]
See #50: unless you explicitly specify `127.0.0.1`, `pigpiod -l` refuses connections from the local host.

**Comment by ambanmba** [comment]
Wonder if it's worth adding to the installation instructions under https://github.com/ebaauw/homebridge-rpi#configure-pigpiod-service which I thought was only for the remote scenario. Maybe add it also to the local section?

**Comment by ebaauw** [comment]
That's actually not a bad idea thanks.
