### ISSUE TITLE
Enhancement: Add latching feature

### ISSUE THREAD

**Issue by fromanza** [ebaauw/homebridge-rpi#102]
Great plugin! Im using homebridge to remotely monitor pi-zero GPIO pins for a door bell application. All works great on WiFi but when I switch to 4G cell network apple homekit seems not to detect the open/close of the button on the GPIO. It only works if I hold the button down for between 3-10 seconds, only then the signal comes through. The time variance  I assume is due to the cell network traffic. I am using a momentary button.

I would like to see a latching function of sorts which will allow a button/doorbell/switch/contact sensor to remain active for a defined period even after stopping pressing the physical button. This will allow the signal to work its way to the remote 4G device before its disabled again. I assume this is an Apple iOS home issue.

Thanks!

**Comment by ebaauw** [comment]
Sorry, I don't think this kind of automation should be provided by Homebridge plugins.  Best use a dummy switch that you set when the GPIO button is pressed, and use an automation to unset it after the defined period.
