### ISSUE TITLE
Plugin search info page update

### ISSUE THREAD

**Issue by TeslaOwnerTips** [ebaauw/homebridge-rpi#103]
Could you update the plugin info page? The page that shows up when we do a plugin search. It's missing that we can access GPIO.
![Screen Shot 2021-07-27 at 12 08 45 PM](https://user-images.githubusercontent.com/78335749/127189291-1958812b-d00e-4aa9-8103-0f435e703e84.png)

**Comment by ebaauw** [comment]
No, I cannot.  This page is not mine; I don’t use Hoobs, I don’t support Hoobs.  I recommend to use a standard Homebridge installation.  See https://github.com/ebaauw/homebridge-rpi/issues/26.
