### ISSUE TITLE
Change RPI updates to debug only

### ISSUE THREAD

**Issue by bloomkd46** [ebaauw/homebridge-rpi#105]
Hello,
Could you please change all of the frequency and temperature updates to this.log.debug instead of this.log. My log is filled up with RPI status updates.
# 
PS what does the smoke detector accessory mean?

**Comment by ebaauw** [comment]
No.  Set _Log Level_ to 0 to prevent Homebridge RPi from issuing log messages, on a per Pi base.

The smoke sensor is there to receive push notifications when the Pi throttles the CPU frequency or experiences under voltage.

**Comment by bloomkd46** [comment]
Ok, thanks

**Comment by bloomkd46** [comment]
Where is the log level setting? The eve app shows it as 2 but when I try to change it it shows a warning symbol

**Comment by ebaauw** [comment]
That’s odd.  Any errors in the log?

**Comment by bloomkd46** [comment]
I figured it out, I wasn't the owner of the HomeKit home so it was blocking me despite the fact that my rank was admin in the home app, it works now. 
Thanks
