### ISSUE TITLE
when using the switch

### ISSUE THREAD

**Issue by HarryMcGill2021** [ebaauw/homebridge-rpi#106]
do you know why the switch times out after 5 seconds as I need to it stay on longer

**Comment by ebaauw** [comment]
See Wiki, https://github.com/ebaauw/homebridge-rpi/wiki/switch-device

**Comment by HarryMcGill2021** [comment]
how do i get rid of the pulse so it can be on for any amount of time

**Comment by ebaauw** [comment]
Don't include `pulse` in config.json.
