### ISSUE TITLE
Relay

### ISSUE THREAD

**Issue by HarryMcGill2021** [ebaauw/homebridge-rpi#107]
I cant get a reply to work with the switch any ideas

**Comment by ebaauw** [comment]
What's your config.json?  Does the relay work when you change the GPIO using `pigs`?  Be sure to use the GPIO (Broadcom) numbers, not the physical PIN numbers.  How did you wire the relay?

**Comment by HarryMcGill2021** [comment]
> What's your config.json? Does the relay work when you change the GPIO using `pigs`? Be sure to use the GPIO (Broadcom) numbers, not the physical PIN numbers. How did you wire the relay?

 "host": "192.168.1.80:8888",
                    "name": "test",
                    "hidden": true,
                    "noPowerLed": true,
                    "noSmokeSensor": true,
                    "devices": [
                        {
                            "device": "switch",
                            "name": "Relay",
                            "gpio": 13
                        }
                    ]
                }
            ],

the relay works then ground is supplied to the vcc pin

**Comment by HarryMcGill2021** [comment]
i  meen the in pin

**Comment by ebaauw** [comment]
I'm sorry, I don't understand what you mean.

A relay typically has a (low voltage) control signal and ground and a (high voltage) input and one or two (high voltage) outputs (normally open and normally closed).  You need to connect the control ground to a ground pin (e.g. physical pin 34), and the control input to GPIO 13 (physical pin 33).  Note that GPIO pins are 3.3V, so the relay must support that.

You can test the relay using `pigs`.  If that doesn't work, Homebridge RPi won't either.  Issue:
```
$ pigs m 13 w
```
to set GPIO 13 to output mode.  Then issue:
```
$ pigs w 13 1
```
to set the GPIO high or:
```
$ pigs w 13 0
```
to set it low.

**Comment by HarryMcGill2021** [comment]
Thanks for you help it works now
