### ISSUE TITLE
Too many entries in the console log

### ISSUE THREAD

**Issue by carlosgamezvillegas** [ebaauw/homebridge-rpi#109]
Hello,

I am having an issue with the way RPi logs the temperature, load, and frequency changes. they are too many entries in the log, I get 7 entries every minute and I was wondering if you could add a way to hide or minimize these log notifications.

Kind regards 
![Log](https://user-images.githubusercontent.com/67111609/133819633-80c91ef5-3900-4f93-a328-560dab82e3d8.PNG)

**Comment by ebaauw** [comment]
Set _Log Level_ to 0 to suppress the info messages.

**Comment by carlosgamezvillegas** [comment]
Thank you ebaauw, where can I set this option? I looked at the settings using HombirdgeUIX and at the documentation and I can’t find the place to set that level to 0.

Thank you

**Comment by ebaauw** [comment]
From HomeKit, using  decent HomeKit app, like Eve.  It's a custom HomeKit characteristic, exposed on the _Temperature Sensor_ service, so you can set the log level per Pi.
