### ISSUE TITLE
Node.js version

### ISSUE THREAD

**Issue by RCdiy** [ebaauw/homebridge-rpi#110]
The plugin "homebridge-rpi" requires Node.js version of ^14.18.0 which does not satisfy the current Node.js version of v15.14.0. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF

**Comment by ebaauw** [comment]
Yes?

**Comment by RCdiy** [comment]
It already has the upgraded version. Maybe its the plugin that needs updating to check for 14.18.0 or above. Why have an unnecessary  log entry for later versions?
