### ISSUE TITLE
Programmable buttons on remote pi's stop working after homebridge loses connection and reconnects

### ISSUE THREAD

**Issue by x10ss** [ebaauw/homebridge-rpi#112]
I have a pi zero with programmable buttons connected to it. Whenever my homebridge (running on another pi) loses connection with it and eventually reconnects, the console is still pulling stats from it but it won't receive programmable switch events until I restart the homebridge service. Thanks for the plugin!

Similar to #95

**Comment by ebaauw** [comment]
Could you try beta v1.3.12-0?  I think I found and tackled the issue.

The beta will bitch about Node v16.13.0, but it should still work with v14.

**Comment by ebaauw** [comment]
In v1.3.12.

**Comment by x10ss** [comment]
It seems to have fixed the buttons after the restart, but I noticed that the Blinkt!s' statuses remain on when the pi reconnects, preventing me from setting a scene to turn all of the lights on. I also noticed an error that I haven't seen before when the pi zero reconnects: "warning: NC (21): unknown handle (-25)". I'll attach the part of the debug log when the pi zero reconnected (unknown handle error at line 112).

Nevertheless, thank you for fixing the issue around the buttons. That will be very helpful going forward because my pi zero tends to restart randomly from time to time, which prevented me from using the buttons at all.

[homebridge.log (2).txt](https://github.com/ebaauw/homebridge-rpi/files/7450031/homebridge.log.2.txt)

**Comment by ebaauw** [comment]
> "warning: NC (21): unknown handle (-25)"

That’s Homebridge ZP trying to close the handle it had before the Pi rebooted (or rather: before `pigpiod` restarted).  Of course, it no longer exists on `pigpiod`.  However, when the Pi was unavailable due to a network issue, `pigpiod` might still have it.

> I noticed that the Blinkt!s' statuses remain on when the pi reconnects

I didn’t change anything there.  The challenge with the Blinkt! is, that you cannot read its state, you can only set it.  According to the log, Homebridge RPi is sending commands to turn the leds off, presumably because that’s the last known state by Homebridge RPi from before the reboot.  Did you refresh or force close and re-open the Home app?

**Comment by x10ss** [comment]
> Did you refresh or force close and re-open the Home app?

The statuses of the lights remain the same in the Home app as they were before the remote Pi restart, even after reopening it. 

> Homebridge RPi is sending commands to turn the leds off

From the log, it seems to me that Homebridge RPi is only sending the commands to the Pi, and not updating the status in the Home app accordingly. Maybe there isn't a part of the protocol that pushes the status to HomeKit after the Pi reconnects?

**Comment by ebaauw** [comment]
> From the log, it seems to me that Homebridge RPi is only sending the commands to the Pi, and not updating the status in the Home app accordingly.

Indeed.  I double-checked the code and did some extensive testing.  Upon start, the Blinkt! LEDs are initialised, and the HomeKit state is set accordingly.  Upon clean shutdown and upon re-connect, the LEDs are initialised, but the HomeKit state isn't updated.

As I mentioned above, you can read the state from the Blinkt!  Currently, Homebridge RPi forces the LEDs off on startup, (clean) shutdown, and on re-connect to make sure they're in a known state.  I can easily update the HomeKit state on (clean) shutdown and on re-connect, but I think it's actually better to reset the LEDs to the last known state, maybe even on startup.

Could you try v3.1.13, that version forces the LEDs to the last known state on startup and (re-)connect.

**Comment by x10ss** [comment]
It seems to work as intended. The lights stay on after the Pi is rebooted. I agree with you that this way works better, but maybe it could also be configurable. It's works perfectly as-is for my case, it's just a suggestion.
