### ISSUE TITLE
Please add the ability to add a lock device to the HomeKit.

### ISSUE THREAD

**Issue by inferutsers** [ebaauw/homebridge-rpi#115]
Please add the ability to add a lock device to the HomeKit. It'll be the same as Switch (it controls relay), but exposed to HomeKit as lock. I'm pretty sure its wouldn't be that hard to implement.

**Comment by ebaauw** [comment]
> I'm pretty sure its wouldn't be that hard to implement.

Not sure why you would think that?  In HomeKit a lock has separate vs current lock states.  I'm not sure how to map that to a single GPIO pin.

**Comment by inferutsers** [comment]
Actually if thats a case you could make it require two GPIOs: one for lock itself (output), and second one for some kind of contact sensor that would tell if the doors are closed or open (input). If the input variable won't be specified meaning there is no contact sensor it could just indefinitely assume that the doors are closed (it shouldn't matter because close to every rpi gpio lock is some kind of electric strike or electromagnet). I've seen that implemented on other hb plugin, and it kinda worked but the plugin itself was really bad and buggy, just an opposite of yours - haven't had a single bug yet. If you could implement that tho I'd be really happy. Please think about it if you can.

**Comment by ebaauw** [comment]
Did you try the workaround from #63?

**Comment by inferutsers** [comment]
Yes! And overall it does the job, but there are some problems:
1. When I set it up, like a day after I did, my friend came over. I showed him what I created and it was good until he got an idea and kinda "broke in" by shouting out to Siri asking to turn on the door and HomePods reacted doing it. If that was exposed as LockMechanism it wouldn't be possible since apple doesn't allow to control locks and security alarms through HomePods.
2. I'm a nerd, and I would ready like to see it in HomeKit as it should be - with lock icon and overall treated as a lock, not a light or a outlet (Switch).

You closed the case you mentioned staying that you can't actually test it yourself - Why not? The simplest it'd be is just to connect an led to one of GPIOs. When you unlock the LockMechanism device, it'd just turn specified GPIO pin to HIGH and locking it would turn it to LOW (or inverted). The CurrentLockState should just follow the TargetLockState and that wouldn't create any problem, it'd just simulate a mechanical lock working really quickly.

**Comment by ebaauw** [comment]
Could you try beta v1.3.14-1?  See [Wiki](https://github.com/ebaauw/homebridge-rpi/wiki/lock-device) for details.

**Comment by inferutsers** [comment]
Thank you so much! It works as expected. My only concern is that the 'pulse' doesn't seem to work. It is necessary when the lock is actual door strike, since you don't want it to stay powered all the time, but for example for 2 seconds or so. I hope that when it comes to official release, that functionality will be there. Other than that I have no complains. Again thank you for your amazing job!

**Comment by ebaauw** [comment]
Ah, I missed the `pulse` part.  So, by default, when the GPIO is low, the lock should be locked.  To buzz it open, you want to set the GPIO high for like 2s, and then revert it to low.  I suppose you still need to use a relay to map the GPIO 3.3V DC signal to the typical 12 to 24V AC used by the strike?

**Comment by ebaauw** [comment]
In beta v1.3.14-2.

**Comment by inferutsers** [comment]
> I suppose you still need to use a relay to map the GPIO 3.3V DC signal to the typical 12 to 24V AC used by the strike?

Yes, I do need a relay. The strike is connected to 12V DC Adaptor and one of the wires is controlled by relay. So yes I do need to set it to HIGH just for 2s and then "lock" it again. 

Overall good job, thanks one again!

**Comment by inferutsers** [comment]
> In beta v1.3.14-2.

In this version everything seems to be ok. Not a single problem.

**Comment by ebaauw** [comment]
Released v1.3.14.

**Comment by MichlW** [comment]
Really thank you for that integration.
I immediately changed from my cmd-based solution to yours and it works like a charme. I am very happy that my request #63 now is implemented.
