### ISSUE TITLE
rpi not being recognised

### ISSUE THREAD

**Issue by khaliqi** [ebaauw/homebridge-rpi#116]
rpi bridge does not recognise hoobs as a pi
![image](https://user-images.githubusercontent.com/92804950/141600991-cf7a8d26-65f5-4e62-87ca-38dfb4728322.png)

**Comment by ebaauw** [comment]
I don’t support hoobs, see #26, and strongly recommend to use a standard Homebridge installation.

As far as I can tell, hoobs have changed Raspberry Pi OS to the extent that Homebridge RPi no longer recognises it.  I need the info requested in #111 to understand the details.

**Comment by ebaauw** [comment]
Could you try beta v1.3.14-0?  That version should be a bit more verbose as to why it thinks the local host isn't a Raspberry Pi.

**Comment by khaliqi** [comment]
hi i ended up using homebridge and it works now thank you
