### ISSUE TITLE
[RPi] warning: heartbeat 7637, drift 8251 - disable this report/monitoring

### ISSUE THREAD

**Issue by fate8383** [ebaauw/homebridge-rpi#118]
Hello,

I know this has been asked to you many times on your other plugins as well. And I know i checked everything so system is fine. But why only your plugins are reporting this as oppose to others are just fine? I really want to disable this monitoring/reporting as it is not correct and I cannot really worry about something node.js is late for something. Could you please tell me how do I disable this in the plugin or in the code, i can modify not a problem. 

Thanks a lot for the great work

**Comment by ebaauw** [comment]
The warning is issued by homebridge-lib, https://github.com/ebaauw/homebridge-lib/blob/3e148c71c07dea0a6fc802311ac2dd4ad62163fb/lib/Platform.js#L292.

**Comment by fate8383** [comment]
Fantastic!
changed this:
if (drift < -250 || drift > 250)
to:
if (drift < -10000 || drift > 10000)

all good now :)

thanks a lot!

**Comment by fate8383** [comment]
Possibly adding this in settings and it persists after updates? I just updated and I hah to redo it.
