### ISSUE TITLE
new installation pigs hwer error

### ISSUE THREAD

**Issue by flexizon** [ebaauw/homebridge-rpi#12]
Hi.
Make a new installation on a raspberry zero w.
Now i got an error

pi@Test:~ $ pigs hwver
socket connect failed
pi@Test:~ $ 

any idee?

**Comment by ebaauw** [comment]
Did you start the `pigpiod` service?  See: https://github.com/ebaauw/homebridge-rpi#enable-pigpiod-service.

**Comment by flexizon** [comment]
> 
> 
> Did you start the `pigpiod` service? See: https://github.com/ebaauw/homebridge-rpi#enable-pigpiod-service.

Yes.
And if i check it on a raspberry zero with the 
pigs hwver
i get the error message

**Comment by ebaauw** [comment]
Did you verify that it’s running and that it’s listening to port 8888?  What’s the output of `sudo systemctl status pigpiod`?  And of `sudo netstat -a -p tcp`?

**Comment by flexizon** [comment]
i found it..
i forgot to set the interface of the remote gpio at on.....
