### ISSUE TITLE
Cant't get status of 2nd RPi

### ISSUE THREAD

**Issue by mesoblaste** [ebaauw/homebridge-rpi#124]
Hello,
I wish to use this plugin to get the temperature of a 2nd Raspberry in HomeKit. Its a raspberry with home assistant installed on it.
I have homebridge installed on my first Raspberry, and I get the temperature in HomeKit without any issue, i configured the 2nd part of the plugin the same way, pointing to the 2nd raspberry ip adress but it doesn't work

I got this in the log : 

> [15/01/2022, 13:30:58] [RPi] warning: HomeAssistant: FO (104): timeout
> [15/01/2022, 13:30:58] [RPi] HomeAssistant: connected to 10.0.0.60:8123
> [15/01/2022, 13:30:58] [RPi] HomeAssistant: disconnected from 10.0.0.60:8123

and after a moment I got this, and homebridge restart : 

> [15/01/2022, 13:31:28] [RPi] warning: HomeAssistant: FC (105): timeout
> [15/01/2022, 13:31:29] TypeError: Cannot read properties of null (reading 'id')
>     at RpiPlatform.checkDevice (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiPlatform.js:266:36)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at RpiPlatform.init (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiPlatform.js:179:7)
>     at RpiPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiPlatform.js:16:46)
> [15/01/2022, 13:31:29] Got SIGTERM, shutting down Homebridge...
> [15/01/2022, 13:31:34] [RPi] goodbye
> [15/01/2022, 13:31:34] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
> [15/01/2022, 13:31:39] [HB Supervisor] Restarting Homebridge...

here is my config :
```
{`
            "name": "RPi",
            "hosts": [
                {
                    "host": "localhost:8888",
                    "name": "HomeBridge",
                    "noPowerLed": true,
                    "noSmokeSensor": true
                },
                {
                    "host": "10.0.0.60:8123",
                    "name": "HomeAssistant",
                    "noPowerLed": true,
                    "noSmokeSensor": true
                }
            ],
            "platform": "RPi"
```

What do I have to do to get access to that 2nd RPi with home bridge?

**Comment by ebaauw** [comment]
Did you follow the steps for [Remote Raspberry Pi Configuration](https://github.com/ebaauw/homebridge-rpi#remote-raspberry-pi-configuration)?

Are you sure you're running `pigpiod` on the other Pi on port 8123 ?!

**Comment by mesoblaste** [comment]
I guess I'm not enough advanced user as I can't succeed the first step... I don't know how to enable pigpiod, my raspberry boot on Homeassistant command line and sudo raspi-config return "unknown command"... Maybe pigpiod isn't available once I installed Homeassistant OS on the raspberry?

**Comment by ebaauw** [comment]
I don’t know Home Assistant.  Do they come with their own Raspberry Pi OS image?  You might try and install `pigpio` through `sudo apt install pigpio`, but I wouldn’t know how to run it as a service on your system.

**Comment by mesoblaste** [comment]
Yes this is a specific OS for raspberry pi. I il try that command on the Homeassistant command line interface and let you know what I get.
Thanks for your answer, and thanks for this plugin I already use with my homebridge raspberry pi
