### ISSUE TITLE
HOOBS install issue

### ISSUE THREAD

**Issue by TDT1969** [ebaauw/homebridge-rpi#125]
I’m unclear if the HOOBS install requires the same pigpiod enablement as a standard Homebridge install.  Since HOOBS is more “plug and play” I thought I’d just try to use their UI to setup…

I installed the plugin on it’s own bridge.  Configured as shown below.  Added to Home app.

Bridge was added successfully but “Button” was not added as an accessory.  Used Eve app to confirm that there is no evidence of any RPi accessories.

Would appreciate any insights on what I’m doing wrong.  Is it a pigpiod issue?

{
    "platform": "RPi",
    "name": "RPi",
    "hosts": [
        {
            "host": "192.168.1.7",
            "devices": [
                {
                    "device": "button",
                    "name": "Button",
                    "gpio": 16,
                    "pull": "up"
                }
            ]
        }
    ]
}

**Comment by ebaauw** [comment]
I neither know, use, nor support Hoobs.  I strongly recommend to use a standard Homebridge installation.   Please contact Hoobs support for issues with Hoobs.
