### ISSUE TITLE
Option to Only Expose Light

### ISSUE THREAD

**Issue by SmolSoftBoi** [ebaauw/homebridge-rpi#127]
I'd like to expose just the light of my Pi, without the CPU temperature.

**Comment by ebaauw** [comment]
Why, if I may ask?

There's no benefit not exposing the CPU temperature, as Homebridge RPi would still need to poll the Pi through the `getState` script for the LED state.

**Comment by EpicKris** [comment]
I'm only interested in seeing my actual room temperature, not device temperatures. My device is in my bedroom, and I'd like to have the light turn off overnight, which I do with its fan.

**Comment by ebaauw** [comment]
Setting `hidden` in v1.3.20 hides the _Temperature Sensor_ and doesn't expose the _Smoke Sensor_, but still exposes the _Lightbulb_ for the LED (on Raspberry Pi models that allow LED control).  Set both `hidden` and `noPowerLed` to prevent the `getState` script from being invoked.
