### ISSUE TITLE
Idea! Question is it possible modify existing device templates for to enhance features? 

### ISSUE THREAD

**Issue by oldskole** [ebaauw/homebridge-rpi#132]
Hi, Just testing Homebridge-rpi first impressions - its great :), and wondered if this plugin can incorporate changes to enable :

1) Use the critical alert for ´Contact´ devices (as used for ´Smoke´ & ´Leak´ detected input devices). Eg enabled via a checkbox toggling on/off Critical alert option, similar to the ´Reversed´ checkbox option for various devices. Eg you may want to enhance the alert level for a ´Panic Alarm´ or ´UPS Backup´ following a supply failure but not for window/door open or closed contact state.

or;

2) Enhance the ´Leak´ & ´Smoke´ devices to have alternative text enabled via a checkbox. when selected this alternative text would be displayed in stead of smoke or leak detected text. In addition it would be advantageous to be able to see when these devices were activated via the ´eve´ history similar to the contact device for audit purposes after the event!

If it is possible to do either would be good, but both would be excellent!

Just my thoughts,  it would benefit users with enhanced practical options for alerts & auditing.

cheers.

         Hugh

**Comment by ebaauw** [comment]
"Alerts" or rather push notifications are handled by Apple; HomeKit accessories (including Homebridge/Homebridge plugins) have to visibility into these.

Under _Home Settings_ in the Home app, you can select which of your devices are allowed to send push notifications to this particular Apple device (yes, you need to configure this on each device separately).  Note that only security-related services can generate notifications, hence the _Leak Sensor_ and _Smoke Sensor_ services.  The message in the push notification is set by Apple; you cannot change it.

**Comment by oldskole** [comment]
ok understood!

Thankyou for the prompt reply!

Hugh
