### ISSUE TITLE
rpi info: error: SHELL (110): getState: script not found

### ISSUE THREAD

**Issue by Ronneke** [ebaauw/homebridge-rpi#133]
I'm running Homebridge on a RaspberryPI 4 in a docker container and want to get access to the GPIO-pins.
I followed the instructions for "Remote Raspberry Pi Configuration" with success except...

The step "pigs shell getState" returns 32512 iso 0; The file getState.json is however created in /tmp and has all data it should have.

The final check (I've run "RPI -H xxx.xxx.xxx.xxx info" from within the terminal of Homebridge) however fails with the message "rpi info: error: SHELL (110): getState: script not found" 
In the log of homebridge I also get the message "My RaspberryPi: warning: heartbeat error: SHELL (110): getState: script not found"

I did the same on a second raspberry pi, with the same result.

Any idea where to look for a solution?
Thx.

**Comment by ebaauw** [comment]
You probably didn't create the `getState` script correctly.  Make sure its contents match https://github.com/ebaauw/homebridge-rpi/blob/main/opt/pigpio/cgi/getState exactly, in particular, that there's no `+++` on the last line.

**Comment by Ronneke** [comment]
Yes! Those +++ made the difference. Deleting them solved the problem for both pi’s. Thx for this rapid answer and solution.

**Comment by Ronneke** [comment]
Yes! Those +++ made the difference. Deleting them solved the problem for both pi’s. Thx for this rapid answer and solution.
