### ISSUE TITLE
Add support for DHT11 or other temperature sensor

### ISSUE THREAD

**Issue by BloomyInDev** [ebaauw/homebridge-rpi#139]
It's could be an good idea !
Some tutorial to use [here](https://www.raspberrypi-spy.co.uk/2017/09/dht11-temperature-and-humidity-sensor-raspberry-pi/)

**Comment by ebaauw** [comment]
I need technical documentation how to read the sensor data from the GPIO pin over `pigpio`, not some end user tutorial.  I cannot use a Python library for Homebridge RPi.

**Comment by BloomyInDev** [comment]
I have trove [this](https://github.com/joan2937/pigpio/blob/master/EXAMPLES/Python/DHT11_SENSOR/dht11.py) or [this](https://abyz.me.uk/rpi/pigpio/examples.html)

**Comment by ebaauw** [comment]
Thanks.  I know the web site from the second link, but never looked into these examples.

The sensor is read using regular `pigpio` functions, and should work remotely.  If I understand the code correctly, you set the GPIO pin low, and then the sensor flips the GPIO pin several times, encoding 40 bits of info, based on the timing between flips: 60-100ms for a 0 and 100-150ms for a 1.  The code sets up a callback, that `pigpiod` calls on each rising edge (when the GPIO changes from low to high).  The callback includes a timestamp, so the timing is handled by `pigpio`.

This looks doable; I might even be able to re-use the existing notification handle.  I ordered a DHT11 and a DHT22; my favourite electronics web store even includes the 10kΩ resisters.

**Comment by BloomyInDev** [comment]
Did that enhancement had some advancements ?

**Comment by ebaauw** [comment]
Sorry, what enhancement?

**Comment by BloomyInDev** [comment]
Did you succeed to implement support for dht11 / dht22
(i didn't need it now)

**Comment by ebaauw** [comment]
In v1.4.0.
