### ISSUE TITLE
Error while update.

### ISSUE THREAD

**Issue by PvdGulik** [ebaauw/homebridge-rpi#141]
Hello, after updating to the latest version of the plug-in, I get the following error.

Did I do something wrong?

![image](https://user-images.githubusercontent.com/9421474/188622731-9e1eb3e1-243d-4233-bd91-8802b3a43996.jpeg)

Thanks!

**Comment by ebaauw** [comment]
This is an error by `npm`, not by the plugin.  I haven’t seen this one before and I have no clue what causes it.   Did you try and just install the `latest` version?  And uninstalling and re-installing the plugin?

**Comment by PvdGulik** [comment]
I tried to remove the plug-in to install it again afterwards.
But in the remove action I get sort of same error-message.![image](https://user-images.githubusercontent.com/9421474/188727768-579f3d79-7efc-4876-9f7c-77ec9ab77518.jpeg)

**Comment by ebaauw** [comment]
As I said before: no clue why this is happening.  I’d try cleaning the `npm` cache and/or manually deleting `/var/lib/homebridge/homebridge-rpi`.  And double-check that your uSD card hasn’t gone bad.
