### ISSUE TITLE
long press trigger

### ISSUE THREAD

**Issue by Olivierbkk** [ebaauw/homebridge-rpi#145]
Hello,

Apparently when using the long press on buttons, the action is triggered after the button is released. 

Is is possible to trigger the action 1 or 2 seconds after starting to press the button rather than after release? This way the user would see the action happen and instinctively know that he can release the button (as it is the case for the Ikea shortcut buttons).

Thanks in advance.

**Comment by ebaauw** [comment]
No.  Unlike most real buttons, the GPIO pin doesn’t report hold, only press and release.  Homebridge RPi uses the duration between these to determine single press vs long press.

**Comment by Olivierbkk** [comment]
Thanks for the answer.
