### ISSUE TITLE
Switch with local button

### ISSUE THREAD

**Issue by tasbarba** [ebaauw/homebridge-rpi#15]
Hi! Is it possible to have a button within the Switch Accessory to be able of wiring a physical switch? Is it expected a dimmer switch accessory also? Thank you!

**Comment by ebaauw** [comment]
Sorry, not sure what you're asking.  There's a `button` device is for an input button connected to the GPIO pin.  The `switch` device is for an on/off output device, like a LED, fan, or relay connected to the GPIO pin.  You could wire "anything" to the relay.  See https://github.com/ebaauw/homebridge-rpi/wiki/Supported-Devices.

I don't yet support "dimmable" output devices connected to GPIO pin in PWM mode, if that's what you mean by "dimmer switch".  I shouldn't be too hard to add support, I just haven't found the time yet.

What device do you want to connect?

**Comment by tasbarba** [comment]
Thanks for your repply! Yes, I know there is a button device, but to use it you need a home hub like a apple tv or iPad. So if there was a option to connect a pyshical switch "inside" the Switch Accessory, like the Sonoff Mini, or a Lutron Caseta for instance, would be better. You wouldn't need two devices inside the Home App, nor a Home Hub, and I think its faster to control as well.

Regarding the Dimmable Switch Device, I was just thinking on a cheap way to add dimmable lights to my setup, using the rasp and some 3rd part hardware. But I don't have a specific device in my mind yet.

Sorry for my long repply. Thank you again and congratulations for your work!

**Comment by ebaauw** [comment]
Basically there's two sorts of switches:
- Wired switches that control dumb devices connected by electricity wire; and
- Wireless switches that control smart devices (incl. wired switches).

In HomeKit these are _Switch_ and _Stateless Programmable Switch_ respectively.  For the latter, you need a Home Hub.  The equivalent devices in Homebridge RPi are `switch` and `button`.

I suppose you could create the equivalent of a Sonoff Mini by using a relay (that's strong enough to switch 110V or 240V AC) connected as `switch` to a GPIO pin.  I wouldn't recommend messing with AC current from the a Raspberry Pi, unless you're a certified electrician (or have that level of knowledge).  It probably easier, safer, and only marginally more expensive to buy a Sonoff Mini and expose that through [homebridge-sonoff-mini-api-rest](https://github.com/myroom/homebridge-sonoff-mini-api-rest#readme).  I have no experience with Sonoff nor with that plugin, though.

**Comment by tasbarba** [comment]
Ok, I got it.

Thank you for your attention!
