### ISSUE TITLE
Feature request: outlet device

### ISSUE THREAD

**Issue by Olivierbkk** [ebaauw/homebridge-rpi#152]
Currently I am using relays connected to the RPi to control lights (device in RPi plugin is "light") but in the Home app it shows a slider, not just an on/off switch - which is not correct for relay control.

I found that if I use an Ikea outlet to control lights, it just shows an on/off switch and I can make home display it as a light.

I cannot find an outlet device in the plugin, am I missing something?

**Comment by ebaauw** [comment]
`switch`?

**Comment by Olivierbkk** [comment]
ohhhh... how did I miss that....?!

just found out that switches can also be set as lights in the home app

Thanks!
