### ISSUE TITLE
Duration parameter

### ISSUE THREAD

**Issue by pawmwijnands** [ebaauw/homebridge-rpi#153]
Could there be added a duration parameter for the switch. So then you can generate a push switch which automatically goes off.
I am using this for several self made remotes on my raspberry.

thanks in advance.

**Comment by ebaauw** [comment]
I suppose you found the `valve` device?

**Comment by pawmwijnands** [comment]
No, I thought i found it. Pulse but thats something different.Valvle device is only set for minutes. I need just need values like 500ms.Op 17 jan. 2023 om 23:28 heeft Erik Baauw ***@***.***> het volgende geschreven:﻿
I suppose you found the valve device?
