### ISSUE TITLE
Heartbeat error? "Cannot open ENOENT"

### ISSUE THREAD

**Issue by r2shyyou** [ebaauw/homebridge-rpi#158]
After the update to 1.8.0 i'm continuously seeing the following error:

`[25/03/2023, 13:35:03] [RPi] Pi: warning: heartbeat error: /sys/class/leds/PWR/brightness: cannot open: ENOENT no such file or directory`

I downgraded to the previous version and the error disappeared. I've since re-updated to 1.8.0.

**Environment:**

Plugin Version: 1.8.0
Homebridge Version: 1.6.0
Node.js Version: 18.15.0
NPM Version: 9.5.0
Operating System: Raspbian

**Comment by ebaauw** [comment]
See #157.

**Comment by r2shyyou** [comment]
> See #157.

i looked at 157 and admittedly don't understand if i need to do something or not (pardon my ignorance). you write "Fixed in v1.8.0." and i've updated to that version, but i'm still getting the error. for what it's worth, the error i'm getting is the following:

`[25/03/2023, 17:52:44] [RPi] Pi: warning: heartbeat error: /sys/class/leds/PWR/brightness: cannot open: ENOENT no such file or directory`

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-rpi/releases/tag/v1.8.0.

**Comment by r2shyyou** [comment]
all set. thought i'd updated the kernel version but i hadn't. all good now. thanks!
