### ISSUE TITLE
heartrate setting

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-rpi#16]
Implement heartrate characteristic for setting the refresh rate.

**Comment by mbierman** [comment]
Will this fix this? 
`[4/15/2020, 1:09:40 PM] [RPi] warning: heartbeat 4, drift 644`

**Comment by ebaauw** [comment]
No, that’s a warning the the heartbeat tick was fired 0.644 seconds late.  If you see a lot of these, with larger numbers, something might be blocking NodeJS.

**Comment by mbierman** [comment]
Thanks I think I have it working now.

**Comment by ebaauw** [comment]
In v1.0.3.
