### ISSUE TITLE
rip  info return error 

### ISSUE THREAD

**Issue by Ogdla** [ebaauw/homebridge-rpi#160]
Good day  Mr ebaauw   ,
I have   a issue configuring  home bridge -rpi  on my  local raspberry . 
$rpi info return this  :
pi@homebridge:/var/lib/homebridge $ rpi info
rpi info: error: /sys/class/leds/PWR/brightness: cannot open: ENOENT no such file or directory   
the file PWR does not  exist  . I have  a  Pi 3B .
Can you pleas help ?

**Comment by ebaauw** [comment]
See #157

**Comment by Ogdla** [comment]
thks  you  very much for your reply .
