### ISSUE TITLE
[Minor, minor issue] Broken URL in Wiki

### ISSUE THREAD

**Issue by ehurrn** [ebaauw/homebridge-rpi#164]
Hello,

On this [page](https://github.com/ebaauw/homebridge-rpi/wiki/Supported-Devices) there seems to be a broken URL. 

This is the URL on the page: https://github.com/ebaauw/homebridge-rpi/Hardware-Monitoring
But it should be: https://github.com/ebaauw/homebridge-rpi/wiki/Hardware-Monitoring (note: /wiki/)

![Screenshot 2023-08-19 at 1 15 47 AM](https://github.com/ebaauw/homebridge-rpi/assets/97811715/78d3b62b-6197-46f9-a398-ab2624cb8ae9)

Thanks in advance!

**Comment by ebaauw** [comment]
Thanks for reporting.  Fixed.
