### ISSUE TITLE
new "raspberrypi" device

### ISSUE THREAD

**Issue by Olivierbkk** [ebaauw/homebridge-rpi#168]
Hello,

After I activated the plugin, I get a new device as follows:

![Screenshot 2023-12-11 at 18 24 08](https://github.com/ebaauw/homebridge-rpi/assets/113991249/b01b0e52-59bd-4cc9-b316-2217730bd59e)

![Screenshot 2023-12-11 at 18 20 56](https://github.com/ebaauw/homebridge-rpi/assets/113991249/7200a557-10ae-432f-91ac-12c3b7ae9fd8)

I did not have this before, is there a way to remove it as it seems to be here without any usage?

Here is my setup:
```
{
            "name": "RPi",
            "hosts": [
                {
                    "host": "localhost:8888",
                    "name": "raspberrypi",
                    "hidden": true,
                    "noFan": true,
                    "noPowerLed": true,
                    "noSmokeSensor": true,
                    "usbPower": false,
                    "devices": [
                        {
                            "device": "switch",
                            "name": "Gate",
                            "gpio": 5,
                            "reversed": true,
                            "pulse": 487
                        },
                        {
                            "device": "switch",
                            "name": "Siren",
                            "gpio": 6,
                            "reversed": true
                        }
                    ]
                }
            ],
            "platform": "RPi"
        }
```

**Comment by ebaauw** [comment]
> is there a way to remove it 

No.  You can exclude it from your Home view and move it to a dummy room.

> it seems to be here without any usage

Only in Apple's Home app.  It's still needed to set _Log Level_ from a decent HomeKit app.
