### ISSUE TITLE
New temperature sensor

### ISSUE THREAD

**Issue by JaKubinaa** [ebaauw/homebridge-rpi#169]
Hi :)

Would it be possible to add another temperature sensor?

I have a DS18B20 sensor that is also one wire, I would like to use it in the sauna.

The dht22 sensor can't handle it. I need something that can handle higher temperatures than the dht22.

Great plugin, thank you.

**Comment by ebaauw** [comment]
Don’t know that one.  Would you have any technical info on it?

**Comment by JaKubinaa** [comment]
There is data sheet
https://pdf1.alldatasheet.com/datasheet-pdf/view/227472/DALLAS/DS18B20.html

There is description of data structure but in polish
https://ntronic.pl/czujnik-temperatury-ds18b20/

**Comment by ebaauw** [comment]
From what I can tell, the sensor's GPIO pin cannot be read through `pigpio` directly, see https://github.com/joan2937/pigpio/issues/60#issuecomment-214872513.

But when 1-wire support is enabled on Raspberry Pi OS, the sensor output is available on a file, `/sys/bus/w1/devices/28-00*/w1_slave`, which could be accessed through `pigpiod`.  Search for `1-wire` on https://abyz.me.uk/rpi/pigpio/examples.html.

I could implement polling the file and parsing its contents relatively easily.  I'm afraid the file name needs to be specified in `config.json`, and, obviously, `/opt/pigpio/access` would need to be added manually, to allow access to the file.  Or maybe it's enough to specify only the device ID, as the file name is derived from that.

Could you please enable 1-wire on your Pi and double-check that a `/sys/bus/w1/devices/28-00*/w1_slave` file is indeed created?  Could you please list the contents of that file (using `cat` when it context text, or `od -c` when it's binary)?  Could you please check that the contents are updated when the temperature changes?
