### ISSUE TITLE
Power State on Reboot

### ISSUE THREAD

**Issue by tasbarba** [ebaauw/homebridge-rpi#17]
Hi ebaauw!

Is it possible to choose the state of the devices in case of a reboot, or power failure?

Thank you!

**Comment by ebaauw** [comment]
Do you mean of devices connected to the GPIO pins when the Raspberry has rebooted?  How would you choose the state?  Through config.json or through a HomeKit automation?  What devices are you thinking of?

To deal with power failures I use a USB power bank as el-cheapo UPS for my Raspberry Pi, see http://raspi-ups.appspot.com/en/index.jsp.

Homebridge RPi re-establishes the connection to `pigpiod` when it fails, but I think it it doesn’t reconfigure the GPIO pins - I need to check.  Also Homebridge RPi would need to detect that the Pi has rebooted vs just a network failure.  The `vcgencmd` script already runs `uptime` to get the system load, so I should be able to make it return the uptime as well.

**Comment by tasbarba** [comment]
Yes! the devices connected to the GPIO pins. In my case I have some relays connected to the raspi and would like to choose its state when the raspi is booted. The state should be chosen through config.json. As mentioned my relays are connected to the Pi running Homebridge.

Thank you!

**Comment by ebaauw** [comment]
v1.0.3 adds a `Restart` characteristic that (briefly) turns on when the Pi has rebooted.  That can be used to trigger HomeKit automations to reset GPIO devices (or other HomeKit accessories).  GPIO pins are now also re-initialised after the Pi reboots.

**Comment by ebaauw** [comment]
Note that v1.1.0 no longer exposes _Restart_, but _Status Fault_ instead.  It reflects whether there's a connection to the `pigpio` server; it changes from GENERAL_FAULT (1) to NO_FAULT when the connection has been re-established (and the GPIO pins have been reconfigured).  I no longer try to detect separately whether the remote Pi has rebooted.
