### ISSUE TITLE
PWR LED on RPI 3B+

### ISSUE THREAD

**Issue by yuvalyitz** [ebaauw/homebridge-rpi#171]
Hi thanks for the package!

I'm trying to use it to control GPIO attached lights.
I noticed that you've added a function to control the RPI power LED,
for some reason, the brightness in my case is controlled through `/sys/class/leds/led1/brightness`.
I revised getState and /opt/pigpio/access accordingly but it seems to still try and change to  `/sys/class/leds/PWR/brightness` which is non-existing in my case,
I suspect it since the Homebridge logs give me:

`[1/13/2024, 6:52:52 AM] [rpi] rpi Power LED: On: warning: set: FO (104): no permission to access file (-137)`

although I made `/sys/class/leds/led1/brightness` free to edit.

Do you think I can change another line to get it to control my power led?

**Comment by ebaauw** [comment]
You’re on an old version of Raspberry Pi OS.  They changed the file to control the LED, see https://github.com/ebaauw/homebridge-rpi/issues/157.

The `access` file just configures which files `pigpiod` is allowed to access.  The file being accessed is specified by the `pigpio` client (or in this case Homebridge RPi).
