### ISSUE TITLE
The Pi itself is exposed as an accessory even if it's configured to be hidden

### ISSUE THREAD

**Issue by delingren** [ebaauw/homebridge-rpi#172]
While exploring this plugin, I found this potential bug. I configured the plugin not to expose the Pi, and all the statuses related to the Pi:
```
{
    "name": "RPi",
    "hosts": [
        {
            "host": "localhost:8888",
            "name": "Doors & Windows",
            "hidden": true,
            "noFan": true,
            "noPowerLed": true,
            "noSmokeSensor": true,
            "usbPower": false,
            "devices": [
              ...
            ]
        }
    ],
    ...
}
```

However, when I add it to Home app on iOS, it reports an accessory which seems to be the Pi. The details sheet shows:
```
Manufacturer   Sony UK
Model          Raspberry Pi 3A+
```

In the room view, it shows "Not Supported". Not that it's a big deal, but it sounds like a bug to me.

**Comment by ebaauw** [comment]
That is conform spec: the `hidden` setting removes the service, but not the accessory itself (as it's needed for Homerbidge RPi to function).  It's an "empty" accessory, with only the _Accessory Information_ service, which Apple's Home app shows as _Not Supported_.
