### ISSUE TITLE
FO (104): no permission to access file (-137)

### ISSUE THREAD

**Issue by Jamyz** [ebaauw/homebridge-rpi#180]
I have a Rpi3 to connect
[7/16/2024, 12:35:16 PM] [Servidor Raspberry Pi 4] Pi3: connected to 10.0.0.154:8888
[7/16/2024, 12:35:16 PM] [Servidor Raspberry Pi 4] warning: Pi3: FO (104): no permission to access file (-137)

I have already  do :
https://github.com/ebaauw/homebridge-rpi#file-access

I have :
```
test@raspberrypi:/opt/pigpio $ ls -l
total 8
-rw-r--r-- 1 root root   33 Jul 16 11:53 access
drwxr-xr-x 2 root root 4096 Mar 30  2021 cgi
```

inside access:
`/sys/class/leds/PWR/brightness w`

Whats wrong ? Thanks

**Comment by ebaauw** [comment]
Version of Raspberry Pi OS vs version of homebridge-RPi.  They changed the filename, see https://github.com/ebaauw/homebridge-rpi/issues/157.
