### ISSUE TITLE
plugin to use to control a 9v valve irrigation system

### ISSUE THREAD

**Issue by klinutzu** [ebaauw/homebridge-rpi#181]
hi, it is possible to use the plugin to control an irrigation system for 9v valves? i need to send a short pulse to the valve to switch on and after a period of time another pulse to an other pin to switch off (the pulses should be sent on 2 different pins to use on an h bridge with relays).

thx

**Comment by ebaauw** [comment]
You can send a pulse on a GPIO pin using the `switch` device, see https://github.com/ebaauw/homebridge-rpi/wiki/switch-device.  Note that GPIOs on the Raspberry Pi are 3.3V, so you might need a relay if your irrigation system expects a 9V pulse.  Homebridge RPi can easily expose two `switch` devices, one to turn on the irrigation, and one to turn it off.

Maybe expose a dummy `valve` device, see  https://github.com/ebaauw/homebridge-rpi/wiki/valve-device, on an unused GPIO, for the timer and a better user experience.  Then add some simple HomeKit automations to turn on the On `switch` device, when the `valve` device is turned on, and to turn on the Off `switch` device, when turned off (automatically, after the duration).  You do need a home hub for HomeKit automations.

**Comment by klinutzu** [comment]
ok, thx. one more question: i need to send these short pulses at a preset time, how can i do this (let' say at 20:50, every day for "ON" and after half hour for "OFF") i don't know how to insert also "time"... pls help me, regards.

**Comment by ebaauw** [comment]
Use time triggered HomeKit automations.
