### ISSUE TITLE
getstate error for remote devices

### ISSUE THREAD

**Issue by fate8383** [ebaauw/homebridge-rpi#182]
[9/4/2024, 1:43:46 PM] [RPi] rpi4b2g: warning: heartbeat error: invalid state: Bad control character in string literal in JSON at position 235
[9/4/2024, 1:43:46 PM] [RPi] rpi3b: warning: heartbeat error: invalid state: Bad control character in string literal in JSON at position 234

I am getting these errors all the time from local hombridge on another rpi which does not throws the error for itself and works fine. I rebooted service and device and still getting these every 15 seconds on hearbeart check intervals. Just change the get state script to the latest one as you suggested in the latest update of the plugin.

remote test:
rpi -H REMOTEIP info
rpi info: error: invalid state: Bad control character in string literal in JSON at position 234

local is fine. 

Edit: removed this line from script
"swap": "$(swapon --show=size,used --noheadings --bytes)",\
it is working for remote devices now but getting the warning of "old getstate is used in the plugin" 

homebridge latest stable
nide.js 20 latest stable
plugin latest stable

**Comment by ebaauw** [comment]
What version of Raspberry Pi OS do you have?

What's the output of the command `swapon --show=size,used --noheadings --bytes` when executed on the Pi?

**Comment by ebaauw** [comment]
Hm, do you have multiple swap files configured?  What's the output of `swapon --show`?

> it is working for remote devices now but getting the warning of "old getstate is used in the plugin"

Just change the line to `swap: 0,` to suppress the warning.

**Comment by ebaauw** [comment]
Yes, the script doesn't take into account that (apparently) there can be multiple swap files.  This is probably an edge case.

Can you disable `/var/swap`, using only the ZRAM partition?  Otherwise, change the script line to only return the last line (assuming `/dev/zram0` is listed last on all Pi-s):
```
"swap": "$(swapon --show=size,used --bytes | tail -1)",
```

**Comment by fate8383** [comment]
> Yes, the script doesn't take into account that (apparently) there can be multiple swap files. This is probably an edge case.
> 
> Can you disable `/var/swap`, using only the ZRAM partition? Otherwise, change the script line to only return the last line (assuming `/dev/zram0` is listed last on all Pi-s):
> 
> ```
> "swap": "$(swapon --show=size,used --bytes | tail -1)",
> ```

"swap": "$(swapon --show=size,used --bytes | tail -1)",

used this and it is working as it should. Thanks
