### ISSUE TITLE
Doorbell based automation

### ISSUE THREAD

**Issue by Olivierbkk** [ebaauw/homebridge-rpi#185]
I have a doorbell setup, it works weel, I get notifications and chime through the homepods but the automations based on doorbell "single" press (in the eve app" dont do anything. Any advice?

Basically I would like to turn on some lights when someone rings the doorbell at night.

**Comment by ebaauw** [comment]
If you get the chimes, Homebridge RPi works OK.  HomeKit Automations run on your home hub.  Double-check that it has a connection to the Homebridge (child) bridge for Homebridge RPi.  Restart your Home hub.  If that doesn’t help, disable the automation on one iDevice, wait for that to sync to your other iDevices, enable the automation, wait for sync and try again.

**Comment by Olivierbkk** [comment]
It worked after restarting the Pi, thanks
