### ISSUE TITLE
Feature request: `fan` device for PWM-controlled fan

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-rpi#188]
See Discord.

**Comment by abko** [comment]
Thank you! Will provide feedback as soon as there is something to test!

**Comment by ebaauw** [comment]
Could you try beta v1.8.25-0?

**Comment by abko** [comment]
@ebaauw Bedankt. Thanks. It's working perfectly. 

Amazing how all these tools work so nicely together. Super easy to install a beta version from HomeBridge UI, change the config, and see it all working in a glitch! 

Thanks a million!

**Comment by abko** [comment]
@ebaauw I was a little bit to fast. From Homekit it seems to be ok, but controlling the Fan from the Home App does not seem to trigger the actual commands. Switching it back to a Lightbulb does work, so it seems not all parts are fully connected yet.
Let me know if there is anything I can do to narrow it down more.

**Comment by ebaauw** [comment]
I suspect turning the fan on won’t work, but changing its speed does?

**Comment by abko** [comment]
> I suspect turning the fan on won’t work, but changing its speed does?

That's correct!

**Comment by ebaauw** [comment]
Could you try beta v1.8.25-1?

**Comment by abko** [comment]
> Could you try beta v1.8.25-1?

@ebaauw Just tested it, and works great, both on/off as well as setting a specific rotation speed.

**Comment by ebaauw** [comment]
Published v1.8.25.
