### ISSUE TITLE
Configuration of this plugin

### ISSUE THREAD

**Issue by misanthrophy** [ebaauw/homebridge-rpi#2]
Hello,

thanks for another sweet plugin from you. I have two questions:

1. Do I need to go through the python script for the fan first? --> https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-fan-shim

2. I do not see a config.json file, so do I just need to install the plugin, go through your guide and thats it??? 

Thanks in advance for your help!

**Comment by ebaauw** [comment]
It’s still very much under development and doesn’t cope with a Raspberry rebooting.  It doesn’t yet expose localhost when running on a Raspberry Pi.  I’m afraid the LED on the Fan SHIM is only exposed when the pi’s hostname is `pi5` And the button is not yet supported.  I’m still not sure how to setup the structure for config.json (or use some config on the Pi) to indicate which gpio pins to expose and how.

Ad 1:  No, you don’t need it.  I find the fan doesn’t like to be stopped and started all the time (it get stuck and won’t start - I used some WD40 contact spray to get it running again), so it’s better to let it run continuously.

Ad 2: You need a `{ "platform": "Rpi" }` entry in the `"platforms"` array.  I haven’t yet implemented any options.

**Comment by inikolaev** [comment]
@ebaauw I'm a bit confused - after plugin installation and adding a new platform entry to the `homebridge` configuration should I be able to see anything in the Home app?

**Comment by ebaauw** [comment]
It still very much work in progress.  Currently, homebridge-rpi only exposes pies that advertise the RFB protocol over Bonjour, see https://github.com/ebaauw/homebridge-rpi#automatic-discovery.  I still need to add a check to see whether homebridge-rpi is running on a pi, and maybe allow for pies to be specified in config.json.
