### ISSUE TITLE
Correct uninstall procedure?

### ISSUE THREAD

**Issue by simont77** [ebaauw/homebridge-rpi#23]
Hi,
after removing the plugin from config.json the accessory still showed up on my iDevices, apparently with no issue but obviously frozen. I had to manually remove the accessory from homebridge cachedAccessory file. Is there any other suggested uninstall procedure? Is it a general issue with homebridge 0.4.53 with dynamic platforms?
Thanks

**Comment by ebaauw** [comment]
It's a general issue with dynamic platform plugins, irrespective of the Homebridge version.
Run `homebridge -R` to remove stale accessories from `cachedAccessories` automatically.

**Comment by simont77** [comment]
ok, thanks.
