### ISSUE TITLE
error GPIO operation not permitted

### ISSUE THREAD

**Issue by Stefan-83** [ebaauw/homebridge-rpi#24]
Hi, 
i try to add a switch for controlling a PIN (GPIO) and get this error: "error GPIO operation not permitted"
Any ideas?
Thanks,
Stefan

> Apr 22 13:10:46 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:46] Homebridge is running on port 51826.
Apr 22 13:10:48 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:48] [RPi] warning: heartbeat 1, drift 375
Apr 22 13:10:48 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:48] [RPi] localhost: Raspberry Pi 3B+ v1.3 (BCM2837, 1GB) - 0000000021700610
Apr 22 13:10:48 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:48] [RPi] localhost: set Serial Number to "0000000021700610"
Apr 22 13:10:48 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:48] [RPi] localhost: set Manufacturer to "Sony UK"
Apr 22 13:10:48 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:48] [RPi] localhost: set Model to "Raspberry Pi 3B+"
Apr 22 13:10:48 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:48] [RPi] localhost: set Hardware Revision to "1.3"
Apr 22 13:10:48 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:48] [RPi] localhost: set Temperature Display Units to 0
Apr 22 13:10:49 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:49] [RPi] warning: heartbeat 2, drift 464
Apr 22 13:10:49 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:49] [RPi] localhost: set Current Temperature to 58°C
Apr 22 13:10:49 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:49] [RPi] localhost: set Frequency to 600MHz
Apr 22 13:10:49 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:49] [RPi] localhost: set Voltage to 1.2V
Apr 22 13:10:49 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:49] [RPi] localhost: set Throttled to true
Apr 22 13:10:49 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:49] [RPi] localhost: set Under Voltage to true
Apr 22 13:10:49 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:49] [RPi] localhost: set Load to 1.73
Apr 22 13:10:50 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:50] [RPi] localhost GarageLadestation: set Serial Number to "0000000021700610-1"
Apr 22 13:10:50 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:50] [RPi] localhost GarageLadestation: set Manufacturer to "homebridge-rpi"
Apr 22 13:10:50 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:50] [RPi] localhost GarageLadestation: set Model to "Switch"
Apr 22 13:10:50 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:50] [RPi] warning: localhost: MODES (0): error GPIO operation not permitted (-41)
Apr 22 13:10:50 ioBrokerGarage homebridge[492]: (node:492) UnhandledPromiseRejectionWarning: Error: MODES (0): error GPIO operation not permitted (-41)
Apr 22 13:10:50 ioBrokerGarage homebridge[492]:     at PigpioClient._onCmdData (/usr/lib/node_modules/homebridge-rpi/lib/PigpioClient.js:397:18)
Apr 22 13:10:50 ioBrokerGarage homebridge[492]:     at Socket.emit (events.js:310:20)
Apr 22 13:10:50 ioBrokerGarage homebridge[492]:     at addChunk (_stream_readable.js:286:12)
Apr 22 13:10:50 ioBrokerGarage homebridge[492]:     at readableAddChunk (_stream_readable.js:268:9)
Apr 22 13:10:50 ioBrokerGarage homebridge[492]:     at Socket.Readable.push (_stream_readable.js:209:10)
Apr 22 13:10:50 ioBrokerGarage homebridge[492]:     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
Apr 22 13:10:50 ioBrokerGarage homebridge[492]: (node:492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Apr 22 13:10:50 ioBrokerGarage homebridge[492]: (node:492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ebaauw** [comment]
I haven't seen this error before.  The unhandled promise rejection obviously is a bug, but not the cause of the problem.

> Apr 22 13:10:50 ioBrokerGarage homebridge[492]: [2020-4-22 13:10:50] [RPi] localhost GarageLadestation: set Serial Number to "0000000021700610-1"

Are you trying to use GPIO pin 1?  This is reserved, see https://www.raspberrypi.org/documentation/usage/gpio/README.md.

**Comment by Stefan-83** [comment]
You're absolutely right. The problem was GPIO pin 1. 
I've switched from "[homebridge-gpio-device](https://github.com/dubocr/homebridge-gpio-device#Configuration)", where wPin1 is not GPIO pin1. 
Issue solved. Thanks :)
