### ISSUE TITLE
Disable/Not use the vcgencmd script

### ISSUE THREAD

**Issue by RamSet** [ebaauw/homebridge-rpi#27]
A feature that enables/disables this info would be great as many do not need to check the state of the temperature and other information on the device. I see a lot of chatter within the log for information i do not use or need.

How can one disable that?

**Comment by ebaauw** [comment]
You cannot.

I'm working on a new version that will allow you change the level of logging.  Also, it will allow you to retrieve the state of the local Pi directly, without going through the `pigpio` socket.

I do need the script to check whether the remote Pi has rebooted.  While making that call, I might as well pass the CPU temperature etc.  I need the Pi accessory: the GPIO accessories are linked to it.  I could not expose the service, but then Home would show a _Not Supported_ tile.

**Comment by RamSet** [comment]
Thank you. 
I understand the need for the script, however there might not be a need for all the other information (CPU temp and etc) as that generates additional data especially when monitoring several raspberries, so an option to i suppose, "select" what data is used within the options, would be great ...

**Comment by ebaauw** [comment]
In [v1.1.0](https://github.com/ebaauw/homebridge-rpi/releases/tag/v1.1.0).
