### ISSUE TITLE
Not working on new setup

### ISSUE THREAD

**Issue by pgodw4** [ebaauw/homebridge-rpi#30]
I did a clean flash on my Raspberry Pi Zero W, using the official Homebridge dmg from here:
https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started

Installed no other plugin except Homebridge-rpi, and had to install pigpiod manually as it wasn't on the Homebridge dmg. When the homebridge-rpi plugin was installed, I added my simple 1 accessory details to the config, no issues there. When the Homebridge service restarts it presents an error as:
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
at RpiPlatform.checkDevice (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiPlatform.js:202:32)
at RpiPlatform.init (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiPlatform.js:143:22)

And then a few more lines which I can copy over if desired. When I try to assess rpi using rpi info, I get the following issue:

pi@homebridge:~ $ rpi info
rpi info: error: TypeError: sched.startsWith is not a function
    at Function.getCpuInfo (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiInfo.js:101:16)
    at async Main.info (/usr/local/lib/node_modules/homebridge-rpi/cli/rpi.js:175:14)
    at async Main.main (/usr/local/lib/node_modules/homebridge-rpi/cli/rpi.js:129:7)

Node.js version - v12.16.3
Npm Version - v6.14.5
Homebridge Config UI X - v4.19.0
Homebridge RPi - v1.1.2

Thoughts?

**Comment by ffaamm** [comment]
I second this, yesterday I upgraded to v1.1.1 and it worked (after I manually updated the scripts, of course), today v1.1.2 doesn't work, even `rpi info` fails.

**Comment by ebaauw** [comment]
My bad.  It's a bug alright.  Will publish a fix shortly.

> and had to install pigpiod manually as it wasn't on the Homebridge dmg.

Hm the Homebridge image is based on Raspbian Lite.  Never tried that myself, I use the full Raspbian Desktop.  Did you install `pigpiod` through `sudo apt install pigpio`?

Thanks to @onzu, the next version of the Homebridge image will include `pigpio` and enable the `pigpiod` service by default, see https://github.com/homebridge/homebridge-raspbian-image/commit/89e8a16ffea024e8b56557fb64a621170b263f02.

**Comment by pgodw4** [comment]
> Hm the Homebridge image is based on Raspbian Lite. Never tried that myself, I use the full Raspbian Desktop. Did you install `pigpiod` through `sudo apt install pigpio`?

Yep. Thanks for the quick response!

**Comment by ebaauw** [comment]
Should be fixed in v1.1.3.

**Comment by pgodw4** [comment]
Nailed it. Thanks a lot for the promptness! Now my heater will turn on tomorrow morning and I won't be freezing cold!
