### ISSUE TITLE
Compatibility with Homebridge 1.1.0

### ISSUE THREAD

**Issue by ffaamm** [ebaauw/homebridge-rpi#31]
Homebridge 1.1.0 has just been released and this error message now shows up in the log:
`The plugin "homebridge-rpi" requires a Homebridge version of ~1.0.4 which does not satisfy the current Homebridge version of 1.1.0. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.`

I understand that this is just an error message raised by Homebridge and doesn't strictly implies problems - it just needs to be tested and update accordingly.
On my own I'm testing if my setup still works fine (but it's quite limited, I use just the `witch` device).

**Comment by ebaauw** [comment]
If it works, it works.  I just haven't tested it.

I now understand that any 1.x version of Homebridge won't introduce any breaking changes, so I'll change the check to use `^` instead of `~`.  Semver works differently for 0.x.y vs 1.x.y, 2.x.y, etc.

**Comment by ebaauw** [comment]
Latest version whitelists any homebridge v1.x.x starting from v1.0.4.
