### ISSUE TITLE
remove old/invalid devices

### ISSUE THREAD

**Issue by Stefan-83** [ebaauw/homebridge-rpi#34]
Hi,
I have deleted some devices (sensors or switches) from the config.json and restarted the homebrigde-service. But the devices are still there in the Home-App.
How can I remove old/invalid devices?

Thanks,
Stefan

**Comment by ebaauw** [comment]
What version of homebridge-rpi are you using?  Stale devices should be removed correctly in v1.1.4.  If not, please attach (or pm me on discord) debug log of startup and `cachedAccessories`.

If you’re on v1.0.x and not yet ready to update, you can delete `cachedAccessories` (after stopping Homebridge), or start `homebridge -R` once with homebridge-rpi removed from config.json completely.  `-R` is the default in latest Homebridge version.
