### ISSUE TITLE
Unknown handle error

### ISSUE THREAD

**Issue by hopestillflies** [ebaauw/homebridge-rpi#36]
I'm setup on a pi zero w running the official homebridge image. 
I have a switch and a button set up in config. When everything boots up and after rpi has shown connected to local host, I get the following error twice.

`localhost: warning: NB (19): unknown handle (-25)`

The result (assuming it's connected to this error, but I'm not sure) is that the switch (output) works, but the button (input) does not respond to button push. 

If I go into terminal and restart pigpiod with a systemctl command, then everything works. But after homebridge restarts I get the unknown handle warning again and the button does not work (until I restart pigpiod).

**Comment by ebaauw** [comment]
Could you capture and attach a debug log file?  I need to see when the warning is given in relation to the debug messages.  See https://github.com/ebaauw/homebridge-rpi#debug-log-file.

**Comment by hopestillflies** [comment]
[homebridge.log.gz](https://github.com/ebaauw/homebridge-rpi/files/4674587/homebridge.log.gz)

**Comment by ebaauw** [comment]
Thanks.  The good news: I can reproduce the problem.  Not sure yet what's causing it, but it seems like Homebridge ZP is trying to initialise the accessory twice on startup.  Could you try and specify the (non-loopback) IP address of the Pi in config.json, instead of `"localhost"`?

> If I go into terminal and restart pigpiod with a systemctl command, then everything works.

Apparently, on re-connect, the accessory is initialised only once.

**Comment by hopestillflies** [comment]
When I put in the IP instead of localhost and restart Homebridge I get another warning and it says 
FO (104): no permission to access file (-137)
Continues to go back and forth between "my ip: Connected to my ip:8888" and that warning.
When this is taking place the accessories still appear in Home and for instance I can turn the switch on and off and it looks in Home like it is on and off, but the actual pins are not responding and there's no registered response in the Homebridge logs.

**Comment by ebaauw** [comment]
Ah, yes, of course.  Homebridge RPi doesn't yet know it's the localhost so it accesses `/proc/cpuinfo` through `pigpio` to get the serial number.  You need to configure [File Access](https://github.com/ebaauw/homebridge-rpi#file-access), just for `/proc/cpuinfo`.  No need to install the `getState` script.

**Comment by hopestillflies** [comment]
We have a winner. That seems to have solved it. Everything starts up, and restarts without the handle warning and with pins functioning (without having to restart pigpiod). I seem to be running full steam now. Thank you.
To recap: Config is set with my IP instead of 'localhost' and I configured file access for /proc/cpuinfo

**Comment by ebaauw** [comment]
Happy that it works now for you.  The `localhost` not working is a bug.  Will have to figure out what's causing it and fix it properly.

**Comment by ebaauw** [comment]
Fixed in v1.1.7.
