### ISSUE TITLE
command failed: vcgencmd measure_temp

### ISSUE THREAD

**Issue by Bartelm** [ebaauw/homebridge-rpi#37]
Today I updated my homebridge setup, including this plug-in. It almost works perfect as before, there's just one warning I get the whole time in the logs:

[5/25/2020, 3:17:39 PM] [RPi] RPi: warning: Command failed: vcgencmd measure_temp

I've already singled out a problem. My user homebridge is not allowed to get the cpu temperature by using the new getState file. When letting this user use sudo, there's no problem:
![image](https://user-images.githubusercontent.com/4353707/82816396-5fa52780-9e9b-11ea-9123-e1f3dee2a0f1.png)

Might this be the problem to the not working measure_temp?

Strange thing is, my main user Pi is able to get the cpu temp by just using the normal cmd without superuser rights. So is this a user rights issue I'm not aware of? How should I tackle this?

**Comment by ebaauw** [comment]
User needs to be in `video` group to execute `vcgencmd`, see README.  Note that the `getState` file is not used for the local Pi.
