### ISSUE TITLE
Don't understand how to use the pulse option on a switch

### ISSUE THREAD

**Issue by Julien-Molina** [ebaauw/homebridge-rpi#38]
I'm trying to control a relay thanks to your plugin but for some reason I can't use the pulse option. So I think i'm not using it properly. What I would like to do is to switch my relay ON for a short period of time and switch back OFF after that. Is this how the pulse is supposed to work ?

In my case the switch is turned OFF after around 20-30 seconds even if I specify a few ms.

My configuration :
{
                            "device": "switch",
                            "name": "test",
                            "gpio": 5,
                            "reversed": true,
                            "pulse": 50
                        },

Can you help me with this issue ?

**Comment by Julien-Molina** [comment]
[5/30/2020, 23:19:29] [Raspberry GPIO] localhost test: On changed from false to true
[5/30/2020, 23:19:29] [Raspberry GPIO] localhost: command WRITE (4) 5 0 
[5/30/2020, 23:19:29] [Raspberry GPIO] localhost: command WRITE (4) => 0

[5/30/2020, 23:20:10] [Raspberry GPIO] localhost test: gpio 5: low
[5/30/2020, 23:20:10] [Raspberry GPIO] localhost: command WRITE (4) 5 1 
[5/30/2020, 23:20:10] [Raspberry GPIO] localhost: command WRITE (4) => 0

**Comment by ebaauw** [comment]
What's you full config?  Did you see any errors in the log during Homebridge startup?

**Comment by Julien-Molina** [comment]
Well I tried again with the new version 1.1.7 and a new version of node 12.17.0 and now it works. I don't what was wrong in the first place. Thanks anyway.

**Comment by ebaauw** [comment]
v1.1.7 fixed a bug where changed GPIO values wouldn't be pushed to Homebridge RPi when `localhost` was used in config.json.  The timer for turning the switch of is started on receipt of the notification.
