### ISSUE TITLE
Only temperature is available

### ISSUE THREAD

**Issue by mwhuss** [ebaauw/homebridge-rpi#40]
I installed and setup the plugin and I only see a single "thermostat" accessory that shows the temperature of `localhost`. It's missing the frequency, voltage, and throttled information.

**Comment by ebaauw** [comment]
Apple’s Home app only supports a limited subset of HomeKit.  Did you try another HomeKit app?

**Comment by mwhuss** [comment]
I installed another HomeKit app and now I do see the extra data under the accessory that's not shown in the Home app. I was under the assumption the plugin would expose multiple accessories with each showing the information. Maybe consider it a feature request 😄

**Comment by ebaauw** [comment]
Or maybe not.  Home would just show a bunch of _Not Supported_ tiles, and you’d hit the Apple imposed limit of 149 accessories per Homebridge instance way sooner.
