### ISSUE TITLE
getState script

### ISSUE THREAD

**Issue by WeltenbummlerKA** [ebaauw/homebridge-rpi#42]
When I follow your instructions I get in Homebridge only the CPU temperature. All other values of the getState script didn't appears. Do I need a syntax to show also the load, the frequency and the voltage?

my JSON:
{
            "name": "RPi",
            "hosts": [
                {
                    "host": "192.168.178.9",
                    "name": "Homebridge"
                }
            ],
            "platform": "RPi"
        }

**Comment by ebaauw** [comment]
You need to use a decent HomeKit app, see https://github.com/ebaauw/homebridge-rpi#prerequisites.

**Comment by WeltenbummlerKA** [comment]
Thank you I see with Eve I get all informations.
