### ISSUE TITLE
Enhancement: expose throttling as smoke sensor

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-rpi#44]
Or fire sensor or something similar in order to get notifications, cf the _Leak_ sensor for Rain in Homebridge WS.

**Comment by ebaauw** [comment]
In v1.1.11.

**Comment by ebaauw** [comment]
Hm, the Pi 3B+ has a soft temperature limit, which defaults at 60°C, where it reduces the CPU frequency from 1400MHz to 1200MHz (`throttled` value 0x00008).  Homebridge RPi currently sets the _Throttled_ characteristic when this happens, and consequently _Smoke Detected_.  This might cause a lot of notifications: even with a heatsink case, my 3B+ Pi-s in the electricity closet hover around 59°C.  You might want to fiddle with `temp_soft_limit` in `config.txt` to prevent this.

Note that this applied to the Pi 3B+ only.  The other Pi models don't have such a soft limit and Homebridge RPi will only generate notifications when they raise to 80°C.  See https://www.raspberrypi.org/documentation/hardware/raspberrypi/frequency-management.md.

**Comment by freddair** [comment]
How can I disable the smoke sensor?

**Comment by ebaauw** [comment]
The sensor cannot be disabled, but you can disable the notifications from the Home app.  Easiest is under home settings, where you see an overview if all sensors for which notifications can be set.

**Comment by freddair** [comment]
Hi and thanks for your reply, I already disabled notifications for my devices. But all family members also smoke detection alarms as a default so everyone is alarmed thinking my house is burning down - i have a Rpi3+ and it hovers around 60 degrees...

I would therefore suggest to make the smoke sensor as an Option in the config, would that be possible?

**Comment by ebaauw** [comment]
> i have a Rpi3+ and it hovers around 60 degrees

See above: you can change the soft limit from `/boot/config.txt`.  I set it to 70°C with the current heat wave; my production Pi 3B+ running deCONZ and two Homebridge instances now hovers around 65°C.

> I would therefore suggest to make the smoke sensor as an Option in the config, would that be possible?

I added a `noSmokeSensor` key, but this feels like disabling the warning light instead of addressing the real issue.

**Comment by freddair** [comment]
Thanks. I already tried to ![image](https://user-images.githubusercontent.com/63143560/90161846-0c54be00-dd94-11ea-8623-66012165bdcb.jpeg)

But it has no effect, maybe I did something wrong?

I now disabled the Smoke Sensor with your new Option and my family members can sleep again, thanks a lot!

**Comment by ebaauw** [comment]
Stupid question, but you did reboot the Raspberry Pi after changing `/boot/config.txt`, didn’t you?

The smoke sensor triggers on throttling and/or under voltage.  Maybe you have an issue with the power?  Check by `vcgencmd get_throttled` to see if under voltage has occurred.  See https://github.com/ebaauw/homebridge-rpi/wiki/Hardware-Monitoring#system-status.

**Comment by freddair** [comment]
Yes I did a sudo reboot after that. vcgencmd get_throttled gets me throttled=0x50000

**Comment by ebaauw** [comment]
That means that both under voltage and real throttling (CPU temperature above 80°C) have occurred.

**Comment by freddair** [comment]
Strange. Eve App shows a constant temperature around 60, with maximum of 62 degrees...

**Comment by ebaauw** [comment]
Homebridge RPi samples the temperature once every 10 minutes; individual peaks might not show in the history.  That’s one of the reasons I created the smoke sensor: to get an instant notification.  Once they reverse engineer the Eve Smoke, I want to add history for the smoke sensor.  I assume that works like the Eve Motion and Eve Door and Window, that actually create a history entry per event, instead of taking periodic samples.

I don’t know if that’s technically possible, but maybe the Pi throttles the CPU to cope with under voltage.  Anyways, these conditions cannot harm the Pi, but could result in a serious drop in responsiveness.

**Comment by sdecaux** [comment]
> > i have a Rpi3+ and it hovers around 60 degrees
> 
> See above: you can change the soft limit from `/boot/config.txt`. I set it to 70°C with the current heat wave; my production Pi 3B+ running deCONZ and two Homebridge instances now hovers around 65°C.
> 
> > I would therefore suggest to make the smoke sensor as an Option in the config, would that be possible?
> 
> I added a `noSmokeSensor` key, but this feels like disabling the warning light instead of addressing the real issue.

definitely the Pi is NOT a smoke detector, so the notification has frightened my family for nothing.
How may I activate this `noSmokeSensor` key?

**Comment by cbrunnkvist** [comment]
Yes, please don't enable such a hack by default - this plugin has nothing to do with smoke detection and shouldn't pretend to do so. _Should_ the user want an alarm signal when CPU throttling is taking place, then add an _optional_ `throttlingAsSmokeSensor` toggle instead.

**Comment by Ghitafjorback** [comment]
I would like to change the temp_soft_limit for my RPI 3B+, but there is no such thing mentioned in the /boot/config.txt on my pi!? I use raspberry by image with Homebridge. Can you guide me how to change the setting for the temp_soft_limit?
Thanks

**Comment by ebaauw** [comment]
Add the setting to /boot/config.txt, see link above.

**Comment by Ghitafjorback** [comment]
Thanks. I misunderstood it. I thought I had to edit the setting from 60 to 70, but now I get that I had to add the sentence temp_soft_limit=70.
Thanks again

**Comment by stevetcsi** [comment]
So I've started playing with this on a RPI 4B(Homebridge/GPIO) as well as an RPI Zero W(remote GPIO). For some reason, I'm getting occasional "General Fault. The accessory reports fault code 0/1" in the Eve home app. It will show smoke detected at the same time.  Checking the vcgencmd get_throttled on both shows 0x0. Temp is 47ºC on the 4B and 36ºC on ZeroW. 

Sometimes restarting HomeBridge will clear it. Sometimes just waiting a while. What can I do to track down what might be causing this?

**Comment by ebaauw** [comment]
Homebridge RPi sets _Status Fault_ when the connection to `pigpiod` on a remote RPi is lost.  I think Apple’s Home app gracefully ignores this (even though it’s a standard, Apple-defined characteristic), but indeed Eve shows this.  _Smoke Detected_ is supported by Home and by Eve.  Both apps should display the same value.  If they don’t try refreshing, force-quitting and restarting the app.  Most likely, the connection between the app (showing the wrong info) and Homebridge was lost.

By default, Homebridge RPi logs all interaction with HomeKit in the Homebridge log.  Run Homebridge in debug mode to log also the interaction with the RPi.  You can set _Log Level_ (in Eve) per RPi to change the level of logging per RPi to debug issues with a single device.  Set _Log Level_ to 3 to log the payload of the interaction with the RPi.

**Comment by stevetcsi** [comment]
Thanks for the info. Will work on getting homebridge running in debug mode, since I've got it running as a service I have to figure out how to launch it as under correct user in debug mode(I still have lots to learn in the linux world)

In any case, I've now removed the second Rpi0 from the setup so everything is on the Rpi4, pigpiod is local. I'm still getting the accessory fault code 1, and is shows Smoke detected in the Eve app(but no smoke in Home app). I've killed both the Home app and Eve app and it comes back the same with fault and smoke yes.

**Comment by shuether** [comment]
Hmm I may have found the problem. iPad reboot seems to have fixed the issue, Eve app was showing fine on iPhone so rebooted the iPad and now its mirroring the iPhone. Thanks for the help!

**Comment by shuether** [comment]
Further to this, it seems the Eve app was messed up on my iPad. Times of events were off by about -7 hours(my GMT timezone offset) even though it showed as being in the right time zone. This has been bugging me for the last few months on anything HomeKit related on this device. Delete of Eve app and re download seems to have fixed it. So all good now! Seems the Eve app was just messed up.
