### ISSUE TITLE
Usage with pwm

### ISSUE THREAD

**Issue by sidharthb0** [ebaauw/homebridge-rpi#45]
Would like to control the backlight of a pimoroni hyperpixel display via HomeKit. 

Currently using wiringpi gpio with the commands:

> gpio -g mode pwm

> gpio -g 19 0 to turn off 

> gpio -g 19 60 to turn on

**Comment by ebaauw** [comment]
In v1.1.12, see also https://github.com/ebaauw/homebridge-rpi/wiki/light-Device.
