### ISSUE TITLE
Feature request: support for temperature sensors

### ISSUE THREAD

**Issue by j0ha** [ebaauw/homebridge-rpi#47]
Hi! I think it would be another great feature to have the support for temperature/humanity sensors like the DHT11 or DHT22 with logging in the eve history.

**Comment by ebaauw** [comment]
I’ll be happy to, if you can tell me how these connect and how to read them.

**Comment by j0ha** [comment]
Yes sure.
The DHT11 and the DHT22 are both sensors which can communicate with the raspberry or other devices like an arduino over a serial signal. The serial signal is delivered by one single pin. The sensor has there additional pins of which are two for powering and one is not in use. More details here: [https://components101.com/dht11-temperature-sensor](url)

The best way to retrieve the data from the sensor is the [BCM2835](http://www.airspayce.com/mikem/bcm2835/) library, which is often used by other homebridge plugins which retrieve data from this sensor kind such as [homebridge-dht](https://github.com/NorthernMan54/homebridge-dht#readme)

**Comment by ebaauw** [comment]
Don’t think I can integrate these.  A single-pin serial protocol requires a precise clock, which cannot be done in NodeJS.  The library you mention contains C++ code to read the sensor.  I don’t want to use that for homebridge-rpi.

Why don’t you use homebridge-dht?

**Comment by ebaauw** [comment]
See #139.
