### ISSUE TITLE
Feature request: heat detector support

### ISSUE THREAD

**Issue by ebisu** [ebaauw/homebridge-rpi#49]
First of all, thank you for creating/sharing this wonderful plug-in. It transformed my 20-years-old home security system into a smart home security system.  All my doors/windows are wired to HomeKit. Homebridge-rpi works like charm!

There is one sensor that I'm not able to migrate properly though. It's a mechanical heat detector. It's commonly used where smoke sensor is not a good option. Kitchen and garage are the most common application as the environment tends to damage smoke detectors.

You can find the technical details of mechanical heat detectors here.
https://www.systemsensor.com/en-us/Documents/5600_Series_Manual_I56-2175.pdf

It would be awesome to allow HomeKit handeling state of connected pin just like smoke detectors.  

Thank you!

**Comment by ebaauw** [comment]
I’m happy to create a `smoke` device to have it exposed to HomeKit as _Smoke Sensor_,  but the tricky part (for me) is how the detectory connects to the Pi. 

Do I understand correctly that it just uses a binary input GPIO signal that is active to indicate the alarm?  Did you already hook it up to the Pi?  Can you try and expose it as a `contact` device and see if Homebridge RPi detects input changes when the detector fires?

**Comment by ebisu** [comment]
Yes, heat sensors use a binary input GPIO signal. I've tested it as a contact device. It's normally opened (no fire), and changed to close when detecting fire. The detection method is based on the spring action of a metal contact, held to the metal chamber by a fusible alloy. When the temperature reaches the alloy’s melting point, the metal contact will depress the diaphragm, causing the electrical contact to close the circuit. It's non-resettable, and cannot be tested unfortunately.

I agreed that exposing heat sensors  as smoke devices would work. Both sensors detect the same hazard in different ways.

**Comment by ebisu** [comment]
Verified! Closing this feature request. Thank you so much!
