### ISSUE TITLE
Connection to localhost refused (under certain conditions)

### ISSUE THREAD

**Issue by Frank-Friemel** [ebaauw/homebridge-rpi#50]
Hi!

First of all: thanks for your excellent work. I am using your Homebridge plugins for a long time now :-)

I've noticed a problem with "homebridge-rpi" when pigpio is being apt-get-installed manually. This is necessary in case someone (like me) starts off by installing the *lite* version of raspbian. In this case the pigpio-daemon starts listening on localhost-tcpV6 and your plugin seems to try to connect via localhost-tcpV4. The homebridge-log throws:

[RPi] error: 127.0.0.1:8888: cannot connect: ECONNREFUSED

My RPi homebridge-config (excerpt) looks like this:

            "name": "RPi",
            "platform": "RPi",
            "hosts": [
                {
                    "host": "localhost",
                    "devices": [
                        {
                            "name": "Außenlicht",
                            "device": "light",
                            "gpio": 23
                        }
                    ]
                }
            ]
        

I was able to work around this problem by editing the gpiod.service script and starting gpiod with options "-l -n 127.0.0.1".

Here are the exact steps to reproduce:

- Install Raspberry OS Lite
- sudo apt-get install pigpio (version 71 will be installed)
- enable and start pigpio daemon
- try "pigs hwver" which results in socket connection problem (please see discussion about it [here](https://github.com/joan2937/pigpio/issues/203))
- update pigpio to version 77 (from sources)
- try "pigs hwver" - which then works
- install homebridge and your homebridge-rpi
- check log file with connection problem

Usually I would have expected that nodejs' implementation of createConnection would try to enumerate the different targets of "localhost" by using "getaddrinfo" which may return more than one ip-address ... but obviously they don't?

Thanks
Frank

**Comment by ebaauw** [comment]
I had another user with a similar issue that Homebridge RPi wouldn't connect to the local `pigpiod` either, unless it was started without specifying `-l`.  I don't know if he installed `pigpiod` manually.

> Usually I would have expected that nodejs' implementation of createConnection would try to enumerate the different targets of "localhost" by using "getaddrinfo" which may return more than one ip-address ... but obviously they don't?

`netstat` showed an IPv4 socket at the Homebridge RPi side and an IPv4/v6 socket on the `pigpiod` side.  My understanding was that NodeJS connects to `::1` alright, but somehow `pigpiod` doesn't treat it as a local connection.  I didn't investigate further, since we found a workaround.  Not sure whether to blame NodeJS or `pigpiod`.  I suppose I could specify `family` to `net.createConnection()` to force an IPv6 connection, but I'm not sure if there are no more IPv4-only Pi-s out there.

What version does `pigpiod -v` report for you?  I have 64 on stretch and 71 on buster.

**Comment by Frank-Friemel** [comment]
my `pigpiod -v` shows 77. 

> I think it's an issue with pigpiod, as pigs didn't work either. I didn't investigate further, since we found a workaround.

Yes, but pigpio team fixed the `pigs` client in version 73 and they think that all other clients should do so as well - not the server. Please see discussion in project pigpio: https://github.com/joan2937/pigpio/issues/203

**Comment by ebaauw** [comment]
I read that issue as it's a server issue alright, but they're not going to fix it anytime soon.  I'm happy to change Homebridge RPi as well, but not sure yet how.  It connects to `localhost`, not to `127.0.0.1`, so I don't understand why it doesn't use `::1`.

**Comment by Frank-Friemel** [comment]
From my point of view the internal implementation of nodejs' createConnection should resolve "localhost" with the different address families and try them one after the other until the connect succeeds. So, you're right: at the end it's not your issue.

Thanks

**Comment by weitzner** [comment]
Just ran into this issue myself - using the "lite" version of the OS, needed to manually install `pigpio` and got a bunch of `ECONNREFUSED`s. One extra wrinkle is that if home bridge is running in a container on the pi, you can't use `localhost` as the host and using the full IP address of the host pi also produces the `ECONNREFUSED` error.
