### ISSUE TITLE
Question about PWM

### ISSUE THREAD

**Issue by Frank-Friemel** [ebaauw/homebridge-rpi#51]
Hi!

The PWM feature you've added recently works great. But I do have a question: E.g. GPIO 18 supports hardware PWM and according to the pigpio API docs there are special calls for it - like `gpioHardwarePWM`. In your code you don't seem to distinguish between the pins. Does the gpio-daemon handle this automatically?

I'm asking because I guess that using hardware PWM signal is of better quality and may be reduces CPU usage?

Thanks

**Comment by ebaauw** [comment]
I have to idea, to be honest.  I don’t (yet) have a (test) setup with a LED, so I haven’t sone any testing or measurement.  I’m just using the default PWM settings, and reports back seem to indicate that that works fine.  I’d suppose they’re good enough to dim LEDS.

Do you actually see increase in CPU usage by `pigpiod` when driving LEDs?  I think it would be unnoticeable with the increased load of NodeJS/Homebridge/Homebridge RPi for polling the PWM duty cycle.

What device do you want to connect requiring a better quality signal?

**Comment by Frank-Friemel** [comment]
It's a white LED stripe. From my experiments I can say: the dimming works really good - no flickering or so. I was just curious if it's worth it to select the pin wisely.
