### ISSUE TITLE
feature wish: reboot button?

### ISSUE THREAD

**Issue by houser42** [ebaauw/homebridge-rpi#52]
Hello,
Not sure about the scope of this plugin, but looking fr a way to create a simple reboot button in Homebridge and was wondering if it is it possible to create such a reboot button for the Raspi with this plugin? Many thanks.

**Comment by ebaauw** [comment]
Creating a button is no big deal, but implementing a reboot is.  On a local Pi you would need root privileges to execute `shutdown`.  For me, that’s a no go.  On a remote Pi, this would require another script to be called through `pigpiod` to execute the `shutdown`.  To me, that would be an unacceptable security risk; anyone on the network could do an unauthenticated shutdown.

**Comment by houser42** [comment]
Thanks @ebaauw 
Sorry for late reply. I understand your priorities. I will look for another way. Many thanks
