### ISSUE TITLE
Feature Request: Increase Switch Pulse max to 60000

### ISSUE THREAD

**Issue by mikebannan** [ebaauw/homebridge-rpi#53]
I'm using RPi to activate the motor on a TV lift. This lift takes 25 seconds to complete. 

(I'm actually running through relays to close an Up switch or a Down switch, to soldered leads on the Up and Down buttons on the motor controller. There are physical cut-off switches to kill the motor when the lift reaches full up/down.)

Since the RPi Switch device only has a 5-second max Pulse, I'm solving it with homebridge-delay-switch to trigger a timer automation to set the RPi Switch to OFF after 25 seconds. Having a 25-second Pulse would be way less complicated.

**Comment by mikebannan** [comment]
The minimum Default Run Time on a Valve in the Home app is 5 minutes. I was hoping for something much shorter.

**Comment by ebaauw** [comment]
That’s a limitation of the Home app.  Use Eve or another HomeKit app.

**Comment by mikebannan** [comment]
Got it. Thanks!
