### ISSUE TITLE
Support for Port Expander

### ISSUE THREAD

**Issue by Frank-Friemel** [ebaauw/homebridge-rpi#57]
Just an idea: pin count of the raspi gpio port is very limited. The PCF8574 is a popular port expander with an I2C interface. It would be great if your homebridge plugin could forward this device. The config could then look like this:

{
          "device": "light",
          "name": "Light",
          "gpio": {
              "PCF8574": 0,
              "port": 0
          }
 }

Where "PCF8574" defines the bus address (up to 8 PCF8574 devices can be addressed) and "port" defines the port number of the addressed PCF8574

**Comment by ebaauw** [comment]
Sorry, I have no experience with SPI and I don't have the port expander.
