### ISSUE TITLE
Button action (sometimes) is not performed

### ISSUE THREAD

**Issue by ondratan** [ebaauw/homebridge-rpi#58]
Hello, 
i am trying to control light with button device. The button (gpio 17) is configured that a short press turns on the switch (gpio 18) and a long press turns off the switch. But very often when the button is pressed the action is not performed.
Thank you for your advice.

"devices": [
  {
    "device": "button",
    "name": "on-off",
    "gpio": 17
  },
  {
    "device": "switch",
    "name": "LED",
    "gpio": 18
  }
]

[RPi] localhost on-off: Programmable Switch Event: Single Press
[RPi] localhost LED: On changed from false to true
[RPi] localhost on-off: Programmable Switch Event: Long Press
[RPi] localhost on-off: Programmable Switch Event: Long Press
[RPi] localhost LED: On changed from true to false
[RPi] localhost on-off: Programmable Switch Event: Single Press
[RPi] localhost on-off: Programmable Switch Event: Single Press
[RPi] localhost on-off: Programmable Switch Event: Single Press
[RPi] localhost on-off: Programmable Switch Event: Single Press
[RPi] localhost LED: On changed from false to true
[RPi] localhost on-off: Programmable Switch Event: Long Press
[RPi] localhost on-off: Programmable Switch Event: Long Press
[RPi] localhost on-off: Programmable Switch Event: Long Press
[RPi] localhost on-off: Programmable Switch Event: Long Press
[RPi] localhost on-off: Programmable Switch Event: Long Press
[RPi] localhost LED: On changed from true to false

**Comment by ebaauw** [comment]
Does the tile in the Home app bounce when you press the button?  From the log, Homebridge RPi exposes the button actions alright.

How did you configure the button actions? In Homekit?  In that case, it’s most likely an issue between Homebridge and your Home hub.  What are you using for that?  Is that already on tvOS or iPadOS 14?  I saw some reports about issues with the Home Pod still running on 13.

**Comment by ondratan** [comment]
Hello ebaauw, thank you for your reply. Its exactly as you wrote. Button actions are configured in homekit, which is on iPad 13.7. Tile is always bouncing when the button is pressed, but the actions are only sometimes performed. 

As you advised I updated iPad to iOS 14, but after update the button tile have disappeared (all others are unchanged) So i set it up again on the iphone with iOS 13.7 and everything works fine. Now just find the button tile on iOS 14 :)

Thank you

**Comment by ebaauw** [comment]
> As you advised I updated iPad to iOS 14, but after update the button tile have disappeared (all others are unchanged)

Damn, looks like iOS 14 no longer displays a tile for the button, when combined with other services in the same accessory.  I still see the buttons exposed by Homebridge Hue, but not those by Homebridge RPi.
