### ISSUE TITLE
Feature Request: Motion Sensor

### ISSUE THREAD

**Issue by zirition** [ebaauw/homebridge-rpi#59]
Thanks for this great plugin!

One of the GPIO device I miss is the Motion Sensor Device on the GPIO. In my case, I use a PIR Sensor attached to a GPIO so it sends the changing state when detect movement.

Could it be possible??

Thanks again!

**Comment by ebaauw** [comment]
Added support for a `motion` device, which is exposed as _Motion Sensor_.  I report _Motion Detected_ when the corresponding GPIO pin is low (as Homebridge RPi configures a pull-up register).  To change that, set `reversed`.

**Comment by ebaauw** [comment]
In v1.1.16.
