### ISSUE TITLE
Doorbell over GPIO IN possible?

### ISSUE THREAD

**Issue by MichlW** [ebaauw/homebridge-rpi#62]
First I want to say thanks for your great plugin. I use it to get the status of my water softener from a potential-free contact as error output wired to a GPIO IN of my Pi 4B.

Today I configured it to also get the event if someone pushes our doorbell button. Actually I use "Contact Sensor" for that purpose.

The Problem is, that i get two notification when pressed and when released. Also today i saw that you started to implement support for "Motion Sensor" over GPIO. Maybe this will resolve my problem, when do you plan to release the new version?

But...

Are you familiar with the accessory **Doorbell**? Maybe this is easy to implement to also use for GPIO sensor input?

**Comment by ebaauw** [comment]
I’ve never used it myself, but if memory serves, the _Doorbell_ service only works in a _Video Doorbell_ accessory.  I need to have a look.

I plan to release a new version this weekend, with the `motion` device and with a separate accessory for the `button` devices as Home on iOS 14 no longer shows them when added to the RPi accessory.

**Comment by ebaauw** [comment]
I tried to expose an accessory with a _Doorbell_ service, but it's not recognised by Apple's Home app.
I double-checked using the HomeKit Accessory Simulator.  The _Doorbell_ service seems to be recognised only in an accessory that also includes an IP Camera.  Exposing a fake camera just for supporting the _Doorbell_ is a bit too much for Homebridge RPi.

**Comment by MichlW** [comment]
Thank you for this information. I will try to configure a motion sensor from your plugin, a lock device and a camera in the same room. I heared HomeKit then acts automatically as such an Video Doorbell and i.e. provides a unlock button and a live image when motion is detected.

Maybe I can update this issue when its done (actually i do not have a suitable camera - searching for a cheap one supporting RTSP).

**Comment by MichlW** [comment]
I opened #63 to also control a door opener from GPIO out using your plugin, that should act exactly as your already implemented switch device.
