### ISSUE TITLE
Dimming bulb with triac - inverted logic

### ISSUE THREAD

**Issue by ondratan** [ebaauw/homebridge-rpi#64]
Hi Eric,
i am trying to dim standard 230VAC light bulb with NextEVO dimmer ( https://www.tindie.com/products/next_evo1/universal-ac-mains-dimmer-mpdmv41/ ) but this dimmer has inverted logic - light is full ON at 0V and full OFF at about 2.85V. Do you think there is a chance to change the logic in the code in raspberry?
Thank you

**Comment by ebaauw** [comment]
Hm, I didn’t implement `reversed` for a `light` device, but I could give it a go.

**Comment by ebaauw** [comment]
@ondratan, could you try v1.1.17-0 (install through `sudo npm -g i homebridge-rpi@beta`).  I think I nailed it, but I have no setup to test this myself.

**Comment by ondratan** [comment]
Hello Eric, yes, it works great. Thank you so much!

**Comment by ebaauw** [comment]
In v1.2.0.
