### ISSUE TITLE
Uninstalling rpi

### ISSUE THREAD

**Issue by X2Stone** [ebaauw/homebridge-rpi#65]
Hi,

First of all, thanks for your plugin, I tested it to see the CPU temp of my Raspberry Pi 4 with Hoobs and it works well.
Now I know my Pi is cool enough (between 37° and 39° thanks to the Argon One case), I have removed the rpi plugin (from Hoobs), restart my Pi... And still have the "CPU temp" and "Smoke Detector" exposed on my Home app... I don't understand why. Is there any dependancies still present on my Pi that I have to manually remove ? Is someone can tell me how to remove rpi completely ?
Thanks a lot for any help.

**Comment by ebaauw** [comment]
Using a standard Homebridge setup, uninstalling the plugin should be enough.  Please contact hoobs support for what needs to be done there.
