### ISSUE TITLE
Hidden option exposes a not supported device to Home App

### ISSUE THREAD

**Issue by MichlW** [ebaauw/homebridge-rpi#66]
When using the option `Hidden - Do not expose a service for the Raspberry Pi itself` to hide the CPU temp sensor, a new device stating "not supported" appears in the Home App.

![image](https://user-images.githubusercontent.com/49558935/98685919-3fddbf00-2368-11eb-8c37-dd877acbc21c.png)

When the "Hidden" option is unselected, the "not supported" device disappears and the temp sensor gets visible again.

I do not want the temp sensor or the device to be displayed. That's what i expect from the "Hidden" option.
Whats the reason for that "not supported" device?

**Comment by ebaauw** [comment]
See #22, #27 and https://github.com/ebaauw/homebridge-rpi/releases/tag/v1.1.4.

**Comment by MichlW** [comment]
Sorry, I looked through the closed issues but found nothing suitable... Shame on me...

Maybe I can address this in the next time by exposing a switch for my relay driven hallway light.
