### ISSUE TITLE
"getState"-Link is wrong

### ISSUE THREAD

**Issue by Peters0nW** [ebaauw/homebridge-rpi#67]
the "getState" Link got a spelling mistake 
  is: https://github.com/ebaauw/homebridge-rpi/blob/master/opt/pigpio/cgi/ **geeState**

 here is that you meant: https://github.com/ebaauw/homebridge-rpi/blob/master/opt/pigpio/cgi/getState

**Comment by ebaauw** [comment]
Thanks!
