### ISSUE TITLE
Adding input capability to switch in addition to switch being only output device

### ISSUE THREAD

**Issue by danalvi** [ebaauw/homebridge-rpi#70]
Hello @ebaauw !

I just programmed my gate to be automised, and I am very excited to continue. My family is sick of my experiments, but they appreciate the outcome after my tries.

My gate has a switch, which connects to a relay and I use “switch” from Homebridge RPi to _output_ an on off value. I, however, also happen to receive, on a different channel, status of the gate i.e. weather it is open or closed. I cannot find any relevant way to do so. I think it would be very helpful if you add a parameter to switch, weather it is taking an _input_ as a switch, or is giving _output_ to a relay (which then acts as a switch). If something like that exists, please point me to it, as I cannot find it from the RPi WiKi.

**Comment by ebaauw** [comment]
A _Switch_ in HomeKit is a controller (user settable), you need to map an input gpio to a sensor of some sort.

I think you want to use `contact` for the input gpio.  In Home you can display that as a door, pretty close to a gate.

**Comment by danalvi** [comment]
OK , understood , I did not know what debouncing is, but now I realised indeed what you mean. Now on a more problematic level, I set up a contact accessory, and is it supposed to receive a 5V to switch on?

If so, it is not doing so, it is already high, and hence not changing state when I provide +5V (from the Raspberry Pi of course).

**Comment by ebaauw** [comment]
> is it supposed to receive a 5V to switch on

NO!  RTFM, https://www.raspberrypi.org/documentation/hardware/raspberrypi/gpio/README.md:
> On Raspberry Pi, all GPIO banks are supplied from 3.3V. **Connection of a GPIO to a voltage higher than 3.3V will likely destroy the GPIO block within the SoC.**

> it is already high

See the Wiki: Homebridge RPi configures a pull up resister, so by default the gpio pin is high.

**Comment by danalvi** [comment]
Thank you, @ebaauw , the issue of subject is resolved. 

>> RTFM

This was not very nice of you, however. There are some learning curves associated with many subjects, and shaming others for not immediately grasping something is not how the world of learning works. I hope you do not exhibit this behaviour further with other people. Also, I think there are ways you could have been more precise in your documentation which you refer to so emphatically.
