### ISSUE TITLE
Power LED: error: 127.0.0.1:8888: cannot connect: ECONNREFUSED

### ISSUE THREAD

**Issue by markbeelen** [ebaauw/homebridge-rpi#72]
Good morning,

I'm getting an error with the new Power LED feature on my local Raspberry3, tried localhost as well as 127.0.0.1: 

_Power LED: error: 127.0.0.1:8888: cannot connect: ECONNREFUSED_

Do I need to add/change some file access? The second Raspberry4 is working fine via the GPIO.

[homebridge.log.txt](https://github.com/ebaauw/homebridge-rpi/files/5719019/homebridge.log.txt)

**Comment by ebaauw** [comment]
Did you start `pigpiod` on the local host?

**Comment by markbeelen** [comment]
No I did not. After enabling/starting and adding /sys/class/leds/led1/brightness to opt/pigpio/access it now works. 
So this is not only necessary on a remote Raspberry but also on the local one.
Thanks.
