### ISSUE TITLE
Can’t hide Light

### ISSUE THREAD

**Issue by tomsteenbakkers** [ebaauw/homebridge-rpi#73]
Today installed the new version with the option for the LightBulb. I changed the config.json so the PowerLed is not exposed as a Light Bulb. But it still show up in the Home.app.

`{
            "name": "RPi",
            "hosts": [
                {
                    "host": "localhost:8888",
                    "name": "Homebridge",
                    "hidden": false,
                    "noPowerLed": true,
                    "noSmokeSensor": true
                }
            ],
            "platform": "RPi"
        },
`

**Comment by ebaauw** [comment]
Oops.

**Comment by tomsteenbakkers** [comment]
😉
