### ISSUE TITLE
ECONNREFUSED but pigpiod is running?

### ISSUE THREAD

**Issue by misterpibbs** [ebaauw/homebridge-rpi#75]
Having this issue where homebridge-rpi is not connecting to the local device port. pigpiod is listening on 8888 but it keeps spitting out econnrefused. Any ideas what I'm doing wrong here?

**Comment by misterpibbs** [comment]
Nevermind I figured it out. Had to kill pigpiod and restart.

**Comment by Reevak05** [comment]
I was having the same problem, thanks!
