### ISSUE TITLE
feature request Garage door. 

### ISSUE THREAD

**Issue by camrun91** [ebaauw/homebridge-rpi#76]
I have two reed switches(contact sensors) that should read the state open or closed then a relay that triggers the opening or closing being able to tie these together via this plugin would be great

**Comment by ebaauw** [comment]
You should be to expose the context sensors as `contact` devices and the relay as `switch` device.  Combining them into a _Garage Door_ service would be possible technically, but is beyond the scope of Homebridge RPi.
