### ISSUE TITLE
Fahrenheit unit for temperature

### ISSUE THREAD

**Issue by bloomkd46** [ebaauw/homebridge-rpi#78]
Could you please add a Fahrenheit option for CPU temperature

**Comment by ebaauw** [comment]
I already expose _Temperature Display Units_.  Other than that, HAP doesn't support Fahrenheit.  Apple leaves it up to the HomeKit app to convert Celsius to Fahrenheit.  I think Home displays °F when you set this in the iOS _Language & Region_ settings.  Never used this myself, though.

**Comment by bloomkd46** [comment]
Ok, thanks
