### ISSUE TITLE
error code 

### ISSUE THREAD

**Issue by flexizon** [ebaauw/homebridge-rpi#8]
try the plugin.
Get strange error.
what do i dont see?

[1/19/2020, 9:45:22 PM] Homebridge is running on port 52967.
[1/19/2020, 9:45:23 PM] [Rpi] warning: testding: FO (104): error no permission to access file (-137)
[1/19/2020, 9:45:23 PM] [Rpi] error: testding: Error: FO (104): error no permission to access file (-137)
    at PigpioClient._onCmdData (/homebridge/node_modules/homebridge-rpi/lib/PigpioClient.js:402:18)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
[1/19/2020, 9:45:23 PM] [Rpi] testding: Raspberry Pi 4B v1.1 (BCM2711, 4GB) - 
(node:3075) UnhandledPromiseRejectionWarning: RangeError: params.id: invalid id
    at new AccessoryDelegate (/homebridge/node_modules/homebridge-rpi/node_modules/homebridge-lib/lib/AccessoryDelegate.js:47:13)
    at new RpiAccessory (/homebridge/node_modules/homebridge-rpi/lib/RpiAccessory.js:30:5)
    at RpiPlatform.checkDevice (/homebridge/node_modules/homebridge-rpi/lib/RpiPlatform.js:196:28)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:3075) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3075) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ebaauw** [comment]
Looks like the `pigpiod` cannot access `/proc/cpuinfo`.  Did you whitelist it?  See https://github.com/ebaauw/homebridge-rpi#file-access.  If so, under what user are you running homebridge?  Can that user open the file?

**Comment by flexizon** [comment]
**YES YES YES!!!!
i am running this on homebridge so i can control it with homekit (apple). If you only install the plugin it's not going to work.
So i did this (the file access thing).** (like you told me to do)


### **_File Access

pigpio provides a hook to access files remotely. homebridge-rpi uses this hook to get the Raspberry Pi's serial number from /proc/cpuinfo and to get the output from the vcgencmd script. These files need to be whitelisted, in /opt/pigpio/access:

$ sudo sh -c 'cat - > /opt/pigpio/access' <<+
/proc/cpuinfo r
/opt/pigpio/vcgencmd.out r
+_**


I am Running this code on a raspberry 4 with 4gb memory .

_{
    "bridge": {
        "name": "xxxxxxxx",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 52967,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Raspberry schuur",
            "hosts": [
                {
                    "host": "111.111.2.77", Youre homebridge ip number
                    "name": "Raspberry schuur",
                    "devices": [
                        {
                            "device": "switch",
                            "name": "Relay1",
                            "gpio": 5
                        },
                        {
                            "device": "switch",
                            "name": "Relay2",
                            "gpio": 6
                        },
                        {
                            "device": "switch",
                            "name": "Relay3",
                            "gpio": 13
                        },
                        {
                            "device": "switch",
                            "name": "Relay4",
                            "gpio": 16
                        },
                        {
                            "device": "switch",
                            "name": "Relay5",
                            "gpio": 19
                        },
                        {
                            "device": "switch",
                            "name": "Relay6",
                            "gpio": 20
                        },
                        {
                            "device": "switch",
                            "name": "Relay7",
                            "gpio": 21
                        },
                        {
                            "device": "switch",
                            "name": "Relay8",
                            "gpio": 26
                        },
                        {
                            "device": "button",
                            "name": "Switch1",
                            "gpio": 4
                        },
                        {
                            "device": "button",
                            "name": "Switch2",
                            "gpio": 17
                        },
                        {
                            "device": "button",
                            "name": "Switch3",
                            "gpio": 18
                        },
                        {
                            "device": "button",
                            "name": "Switch4",
                            "gpio": 27
                        },
                        {
                            "device": "button",
                            "name": "Switch5",
                            "gpio": 22
                        },
                        {
                            "device": "button",
                            "name": "Switch6",
                            "gpio": 23
                        },
                        {
                            "device": "button",
                            "name": "Switch7",
                            "gpio": 24
                        },
                        {
                            "device": "button",
                            "name": "Switch8",
                            "gpio": 10
                        }
                    ]
                }
            ],
            "platform": "Rpi"
        }
    ]
}_

on this board. The only problem with the board is... they make it like off is on and on is off. 

I h
![raspboard](https://user-images.githubusercontent.com/60076441/72754358-d8cbff80-3bc7-11ea-9648-f76cb7b6f2dd.jpg)


Working great!! 
now when i leave my home all lights go out in my shed

**Comment by flexizon** [comment]
Other question.
Should it work with wifi? did you test it?

**Comment by ebaauw** [comment]
> The only problem with the board is... they make it like off is on and on is off.

Did you connect the light to the relay NO or NC output?  Anyways, I’ll see if I can add a setting per port to indicate that the on/off logic is reversed.

Are those push buttons on the board?  Did you try _Double Press_ and _Long Press_ on them?

> Should it work with wifi?

Not sure where you want to use WiFi?  Looks like you’re running homebridge on the Raspberry Pi to which the board is connected?  Yes, homebridge should work over WiFi, but wired Ethernet might be more reliable.

**Comment by flexizon** [comment]
> 
> 
> > The only problem with the board is... they make it like off is on and on is off.
> 
> Did you connect the light to the relay NO or NC output? Anyways, I’ll see if I can add a setting per port to indicate that the on/off logic is reversed.
> 
they just made a design fault with the pull up diode.
dont ask me why. But any other relay boards works fine.

> Are those push buttons on the board? Did you try _Double Press_ and _Long Press_ on them?
> 
Yes push buttons. i personly do like the double press and long press. give some new ideas.

> > Should it work with wifi?
> 
> Not sure where you want to use WiFi? Looks like you’re running homebridge on the Raspberry Pi to which the board is connected? Yes, homebridge should work over WiFi, but wired Ethernet might be more reliable.


Wifi is sometimes just that little bit more easy for far away things.

**Comment by ebaauw** [comment]
v0.0.5 has a `reversed` setting for `button`, `contact`, and `switch` devices.

**Comment by flexizon** [comment]
this one is also important

### _Configure pigpiod Service

Raspbian comes with a service definition for pigpiod, in /lib/systemd/system/pigpiod.service. By default pigpiod won't accept remote connections, due to the -l option. To enable remote connections, run sudo raspi-config and set Remote GPIO (P8) under Interfacing Options (5). This will create a drop-in configuration in /etc/systemd/system/pigpiod.service.d/public.conf, removing the -l option. After that, reload the daemon by:

$ sudo systemctl daemon-reload

Enable pigpiod Service

To enable and start pigpiod as a service, issue:

$ sudo systemctl enable pigpiod
$ sudo systemctl start pigpiod

To check that the service is running, issue:

$ pigs hwver
10494163_


> 
> 
> v0.0.5 has a `reversed` setting for `button`, `contact`, and `switch` devices.



> 
> 
> v0.0.5 has a `reversed` setting for `button`, `contact`, and `switch` devices.

going to test it

**Comment by flexizon** [comment]
v0.0.5 has a reversed setting for button, contact, and switch devices.

going to test it

Its working for relay switches. On is On on the board. But stil its wierd that they make the board diffrent.

**Comment by tjitsejdevries** [comment]
Im having difficulty installing the vcgencmd script. Do I have to copy paste the code in nano and save it as an .sh? Can you elaborate on the instructions?

**Comment by ebaauw** [comment]
Copy/paste the text (from `sudo` up to and including the line with only `+`) into the shell.  That will create the script.  Next, copy/paste the line with `chmod` (not including the `$` prompt), to make the script executable.  Probably need a `sudo` before `chmod` as well...

> Secondly, when i test by doing pigs shell vcgencmd, I get 32256 as response

If `pigs shell vcgencmd` returns anything other than 0, the script hasn't run properly, see http://abyz.me.uk/rpi/pigpio/pigs.html#SHELL.
