### ISSUE TITLE
“Motion” device doesn’t show up in Home app

### ISSUE THREAD

**Issue by vatrushka** [ebaauw/homebridge-rpi#81]
Hi! Thanks for this great plugin. I’m trying to use it to read signal of PIR sensor connected to Raspberry GPIO 2. I added “motion” device, but it’s not showing up in Home. Below is my config json. I double checked that `pigpio` is running, and it is. I also added `button` device just to test and it shows up in the app just fine. What could be the problem? Thanks!

```
        {
            "name": "RPi",
            "hosts": [
                {
                    "host": "localhost",
                    "name": "x.x.x.x",
                    "hidden": false,
                    "noPowerLed": false,
                    "noSmokeSensor": false,
                    "devices": [
                        {
                            "device": "motion",
                            "name": "Motion",
                            "gpio": 2,
                            "reversed": false
                        },
                        {
                            "device": "button",
                            "name": "button",
                            "gpio": 4,
                            "reversed": true
                        }
                    ]
                }
            ]
```

**Comment by ebaauw** [comment]
Did you check another HomeKit app?  Home on iOS14 sort of hides the sensors on the top of the screen.  Press the circle to see a popup with the traditional tiles (or go straight into the _Settings_ popup in case you only have one sensor).

**Comment by vatrushka** [comment]
I noticed the following line in the log output `[RPi] warning: ignoring Pi Motion sensor: 2: invalid gpio`. Didn't know I can't connect sensors to that pin. Changed pin to GPIO 4 and it worked! Thank you!

**Comment by ebaauw** [comment]
It depends on the Pi model which GPIOs are available.  I got the info from http://abyz.me.uk/rpi/pigpio/.
