### ISSUE TITLE
Enhancement: Option to reduce logging

### ISSUE THREAD

**Issue by wifwucite** [ebaauw/homebridge-rpi#83]
It would be nice to have an option to reduce/disable logging by this plugin. Currently it sends a log message every 15s. Since I am running homebridge on a pi with SD card I would like to reduce logging and hence writes to the card.

**Comment by ebaauw** [comment]
It’s already there: see the _Log Level_ characteristic in Eve.

**Comment by wifwucite** [comment]
Oh right, I missed that, thanks!

**Comment by imposibrus** [comment]
Is there a possibility to set this characteristic without Eve? Maybe some option can be added in HomeBridge config?
![image](https://user-images.githubusercontent.com/3369328/109548462-ba7c4700-7add-11eb-8941-16515b07e80a.png)

**Comment by ebaauw** [comment]
You can use any HomeKit app, just not Apple’s Home app, as it doesn’t support custom characteristics.
