### ISSUE TITLE
question! what sensor is using for smoke detector?

### ISSUE THREAD

**Issue by toshibochan** [ebaauw/homebridge-rpi#85]
what sensor is using for smoke detector on raspberry pi? is this MQ135 sensor?

**Comment by ebaauw** [comment]
It’s a virtual sensor that triggers when the Pi’s temperature is so high that it starts throttling the CPU speed, or when the Pi reports under voltage.  I don’t know what onboard sensors the Pi uses, don’t think they’re listed on https://www.raspberrypi.org/documentation/hardware/raspberrypi/README.md.

Home only provides notifications for security-related sensors, so exposing a virtual leak sensor is my trick to get notifications when my (headless) Pi throttles or experiences under voltage.

**Comment by toshibochan** [comment]
So is not smoke or gas detector?

**Comment by ebaauw** [comment]
No

**Comment by GerhardLang** [comment]
Is there a virtual sensor possible that can be triggered manually i.e. By a combination of other sensors, door open and rain for example.
