### ISSUE TITLE
RPi used for door contact sensors, warning in log

### ISSUE THREAD

**Issue by Stevenlgts** [ebaauw/homebridge-rpi#87]
Thank you for the most excellent plug-in!! 
I have three door sensors from my wired alarm system connected to my Raspberry Pi each as its own GPIO pin. The other sensor wire is connected to the RPi ground. No resistors are used. The door sensors are no longer connected to the alarm control panel. The door sensors are configured as a contact sensor. The pulse is set at 1000 ms. Everything works fine but I get a warning in my log. My log gives the following warnings and not sure what they mean.

[15/03/2021, 19:35:14] [RPi] warning: config.json: hosts[0]: devices[0]: pulse: invalid key
[15/03/2021, 19:35:14] [RPi] warning: config.json: hosts[0]: devices[1]: pulse: invalid key
[15/03/2021, 19:35:14] [RPi] warning: config.json: hosts[0]: devices[2]: pulse: invalid key
![image](https://user-images.githubusercontent.com/79030331/111240699-afd7ac80-85c9-11eb-9774-d3d3a2f001e8.png)

Any ideas? Thanks.

**Comment by ebaauw** [comment]
That `pulse` is not a valid key for `contact` devices, see Wiki.

**Comment by Stevenlgts** [comment]
Thank you for the quick reply. I have removed the pulse command in my config and the warning is no more!
