### ISSUE TITLE
heartbeat warning

### ISSUE THREAD

**Issue by 1rado1** [ebaauw/homebridge-rpi#9]
Hi, 
I am getting `[Rpi] warning: heartbeat 1, drift 365` and also some node related errors:
`TypeError: events.once is not a function`
As for now, node.js v. 12.x is not possible for me, since other Homebridge plugins are not compatible, I am forced to use stable version of 8.x - are you about to optimize for older versions?

**Comment by ebaauw** [comment]
I don't think NodeJS v8 supports `events.once()`, so homebridge-rpi will not work with that version.

I develop and test my plugins against the latest LTS version of NodeJS, currently v12.14.1.  I will not spend any time on testing against or porting to other versions.

**Comment by 1rado1** [comment]
You are right, it doesn't support it. 

I totally understand, I have tried to install 12.14.1 and get it work with other plugins, but I am reverting back, as it is not possible at the moment. So I need to look for another plugin to control GPIO which works with 8.x

Thank you for all the info, I appreciate it
