### ISSUE TITLE
Contact Sensor state being set to 1 

### ISSUE THREAD

**Issue by Stevenlgts** [ebaauw/homebridge-rpi#90]
Sir,
I have three contact sensors connected thru RPi, and all was working perfectly. When the front door opens, the contact sensor is triggered, and the sensor's state should change from 0 to 1. When the door closes, it should change the sensor state back from 1 to 0. I noticed that the front door sensor was showing it was open. I checked the door, and it was closed. I tested the contact sensor, and it is working properly. 
![image](https://user-images.githubusercontent.com/79030331/113454262-75458080-93cd-11eb-8690-6dcc67ebf60f.png)
I noticed in the log that when restarting the home bridge, the front door sensor state was being set from 0 to 1. An image of the log entry is listed below.
![image](https://user-images.githubusercontent.com/79030331/113447757-22190100-93c0-11eb-97dc-f8c92e687cc3.png)
All three contact sensors are configured and wired similarly are were all working properly at one time (on separate GPIO pins). 
![image](https://user-images.githubusercontent.com/79030331/113454453-e2f1ac80-93cd-11eb-95fb-00acd0dc346e.png)
Any thoughts on why the sensor state is being changed and how I can prevent this from happening?

Thank-you,
Steve

**Comment by ebaauw** [comment]
Homebridge RPi changes the state of the sensor, when the state of the associated GPIO pin changes.  For input pins, it doesn't change the pin state ever.  On startup, Homebridge RPi configures the pin (in case of `contact`: for input and with a pull-up resistor, see the [Wiki](https://github.com/ebaauw/homebridge-rpi/wiki/contact-device)), but it does **not** change the pin state.

Is Homebridge RPi running on the Pi itself, or is it controlling a remote Pi?  When you say "restart", are you restarting only Homebridge, or also `pigpiod`, or even rebooting the Pi?

How did you wire the sensors?  Normally, the sensor would connect the GPIO pin to ground (low) when closed (contact detected).  HomeKit uses _Contact Sensor State_ value 0 for this.  When the contact is broken, the pin is pulled high by the internal pull-up resistor, and Homebridge RPi sets the _Contact Sensor State_ value to 1.

**Comment by Stevenlgts** [comment]
First, thank you for your assistance.
Homebridge is running off of an RPi 3+. All contact sensors are connected to a separate GPIO pin, and the other lead is connected to the ground pin. I have restarted the homebridge application and the RPi. I have not restarted the pigpod. I'm kind of new at this, so I have been mostly following youtube setup videos, so I'm not exactly sure how to restart pigpod or why it would need to be restarted. Once I started having this issue, I did switch the front door GPIO pin from 15 to 23. I made the necessary corrections in your app and restarted the homebridge and RPi. Ultimately, the issue is that the pin is being set at a contact sensor state of 1. How this is happening is unknown to me. I have completely removed the contact sensor and connected the contact sensor's wires. This should result in the contact sensor state of 0, but it does not have any effect. Somehow the pin is being pulled high and staying in that state regardless of the contact sensor's status.
Thank-you,
Steve

**Comment by ebaauw** [comment]
The Pi (re)sets mode of the GPIO pins on boot.  Different pins have different defaults, see https://www.raspberrypi.org/documentation/hardware/raspberrypi/gpio/README.md:
> All GPIO pins revert to general-purpose inputs on power-on reset. The default pull states are also applied, which are detailed in the alternate function table in the ARM peripherals datasheet. Most GPIOs have a default pull applied.

You can override these defaults in `/boot/config.txt`, see https://www.raspberrypi.org/documentation/configuration/config-txt/gpio.md.

**Comment by Stevenlgts** [comment]
Eric,
I created a contact sensor named test on GPIO 21. Upon restarting homebridge, it set the pin's state to 1, just as it is doing to my other contact sensor (front door). If you notice, it specifically calls out those two contact sensors (Front Door and Test). I have two other contact sensors (Back Door and Garage Entry) that are not mentioned at all in the coding, and they work perfectly. I have moved the Front Door sensor to several different GPIOs with the same result. It appears to me that the GPIO is not the problem. All the RPi GPIOs greater than 8 default to low.
These two lines of code set the state of the sensor to 1 when it should be 0 like the other two contact sensors:
[04/04/2021, 07:29:34] [RPi] raspberrypi Front Door: set Contact Sensor State to 1
[04/04/2021, 07:29:34] [RPi] raspberrypi Test: set Contact Sensor State to 1
This is obviously happening in the RPi plugin. Why is this happening, and how can it be stopped? 
![image](https://user-images.githubusercontent.com/79030331/113508940-7931e980-9518-11eb-9626-f4ccaf797a2f.png)
![image](https://user-images.githubusercontent.com/79030331/113509106-623fc700-9519-11eb-9916-718448bcceef.png)

**Comment by ebaauw** [comment]
Please capture and attach a debug log file, see https://github.com/ebaauw/homebridge-hue/wiki/FAQ#homebridge.

**Comment by Stevenlgts** [comment]
Eric,
Thanks again for your assistance. I have attached the debug log file. These five lines standout as the issue.
[04/04/2021, 14:43:32] [RPi] initialised
[04/04/2021, 14:43:32] [RPi] raspberrypi Garage Entry: gpio 14: low
[04/04/2021, 14:43:32] [RPi] raspberrypi Back Entry: gpio 18: low
[04/04/2021, 14:43:32] [RPi] raspberrypi Front Door: gpio 15: high
[04/04/2021, 14:43:32] [RPi] raspberrypi Test: gpio 26: high

[homebridge.log.txt](https://github.com/ebaauw/homebridge-rpi/files/6255242/homebridge.log.txt)

> Are you sure you're using the right pin?
Again, it was working before. I used GPIO pins 14, 15 & 18 since they were all inline. 

>  If you are, this sounds like a broken wire, or a too long wire with too much resistance to pull the pin low. 
I tested continuity of the circuit when the switch was open and closed. The circuit and contact sensor is working properly. The length of the wire is shorter than the back door sensor wire which is working perfectly. 

> What if you connect the GPIO directly to the ground using a jumper wire?

I double and triple checked to see if I messed up somewhere but connections are as they should be. Again, it was once working.

Thank-you,
Steve

**Comment by ebaauw** [comment]
> [04/04/2021, 14:43:32] [RPi] raspberrypi: command BR1 (10) => 343966207

`pigpiod` reports GPIO 14 and 18 as low and GPIO 15 and 26 as high (it's a bitmap 0x148081FF).  There's nothing I can do about that.  As you can see from the log, Homebridge RPi sends the same configuration commands to all four GPIOs.

You can check this manually by shutting down Homebridge (or unconfiguring the GPIO) and replay the setup by hand:
```
$ pigs modes 26 r
$ pigs pud 26 u
$ pigs r 26
```
The first command sets GPIO 26 to input; the seconds selects the pull-up resistor; the third reads the state.  See `man pigs` for details.

> I double and triple-checked to see if I messed up somewhere, but connections are as they should be.

Did you try and switch the wires and pins, e.g. use the Garage Entry wires on GPIO 15 and the Front Door wires on GPIO 14?

**Comment by Stevenlgts** [comment]
Any thoughts on how I can get another GPIO pin to behave properly? All I need is one for the front door.

> Did you try and switch the wires and pins, e.g. use the Garage Entry wires on GPIO 15 and the Front Door wires on GPIO 14?

No, but I will try it.

**Comment by ebaauw** [comment]
I’ve never seen a GPIO pin misbehave.  The documentation suggests it’s possible to fry the GPIO block (by connecting a pin to more than 3.3V), but I have no experience with that (and hope to keep it that way).  I would think this would break all GPIOs in the block (i.e. 0 to 31), not just one or a few.

I do have some experience with bad connections.  The header of one of my Pi-s had one pin that was 2mm lower than the others, sticking out at the bottom.  It made contact with the bottom plate of my heatsink case.  This was the pin used by the real-time clock on the RaspBee II, which obviously wouldn’t work.  Cost me a couple of days to find this out (was the first time I used the RaspBee II).  Double-check the connections of the header to the board, double-check that the wires aren’t broken and make good contact.  You might want to use [piscope](http://abyz.me.uk/rpi/pigpio/piscope.html) to monitor the GPIO states while testing pins and wires.

I also have quite some experience, unfortunately, with multiple programmes or add-on boards using the same GPIO pins, causing a conflict.  GPIO 14 and 15 are used by the Pi’s serial port.  Make sure it’s disabled in `raspi-config`.

**Comment by Stevenlgts** [comment]
Thank you for your assistance. I figured it out and it is was a wiring issue. My ground wire for the front door sensor was on the GPIO4 and not the ground terminal next to it. Thank you for your support and patience. You have a great product and fantastic support!
All the best,
Steve
