### ISSUE TITLE
Plugin breaking HOOBS

### ISSUE THREAD

**Issue by recoi1er** [ebaauw/homebridge-rpi#91]
Updated the Raspberry Pi 4 firmware yesterday to 5.10 and then later noticed an issue with the plugin, not sure if related but happened around same time and makes sense that something changing in the firmware could break something with this plugin.

My log shows:

4/6/2021, 2:30:30 PM [RPi] Initializing RPi platform...
4/6/2021, 2:30:30 PM [RPi] homebridge-rpi v1.3.0, node v14.16.0, homebridge v1.3.3, homebridge-lib v5.1.0
4/6/2021, 2:30:30 PM [RPi] warning: config.json: plugin_map: invalid key
4/6/2021, 2:30:30 PM Error loading platform requested in your config.json at position 5

config for plugin:

```
[
    {
        "host": "localhost"
    }
]
```

**Comment by ebaauw** [comment]
I have no idea what’s happening.  The error isn’t issued by Homebridge RPi.  I don’t know nor support hoobs.  Best contact hoobs support.

**Comment by recoi1er** [comment]
4/6/2021, 2:30:30 PM [RPi] warning: config.json: plugin_map: invalid key

This error isn’t issue by the plugin?

**Comment by ebaauw** [comment]
That’s just a warning.
