### ISSUE TITLE
Homebridge needs a restart if rpi disconnects

### ISSUE THREAD

**Issue by shuether** [ebaauw/homebridge-rpi#95]
When the rpi gets disconnected from Homebridge, it won't reconnect until I restart the homebridge instance. I currently have homebridge running on another computer and the rpi is just setup for GPIO access. Would be nice if the Homebridge could retry the connection every xx seconds if the connection drops.

**Comment by ebaauw** [comment]
Homebridge RPi tries every 15 seconds to contact the Pi and reconnect if it again becomes available.  You should see warnings in the log, when it cannot connect to the Pi.  I don't know why it doesn't in your case.  Please capture and attach a debug log file, see https://github.com/ebaauw/homebridge-hue/wiki/FAQ#homebridge.

**Comment by ebaauw** [comment]
I refactored the heartbeat logic.  I think there might have been a rare race condition where Homebridge RPi wouldn't reconnect to a re-appearing remote RPi, but without logs, I cannot confirm.

**Comment by ebaauw** [comment]
Found another case where socket would hang when network is disconnected (e.g. pulling the ethernet cable on the remote RPi).  This would cause Homebridge RPi to wait indefinitely for the command response.  Now guarding commands with a timeout.

**Comment by shuether** [comment]
Mine has been reconnecting great for the last week or so,  so I think the heartbeat logic did it. Great you fixed another potential one!
