### ISSUE TITLE
 homebridge-rpi running in a LXC container - warning: vcgencmd: cannot spawn vcgencmd: ENOENT

### ISSUE THREAD

**Issue by uli-rpi** [ebaauw/homebridge-rpi#97]
Iv'e installed homebrige in a unprivileged LXC container on rasperry buster. 
Homebridge-rpi runs in this container. The container uses it's own IP-Adress via virtual bridge.
The idea is, connect to the real rasperry (also the host of the container) as a remote configuratrion. The getState script and the following steps on the remote raspi was successfully installed, the **rpi -H 192.168.... info** command on the homebridge raspi (container) works fine. 

But every 15 sek. there is an warning in the homebridge log -> RPI-DEV Server: warning: vcgencmd: cannot spawn vcgencmd: ENOENT.

I've talking with Eric on discord abut this issue, 
we checked my configuration it seems to be correct. He asked me to open an issue and provide the contents of /proc/cpuinfo and of /proc/1/sched in the container as well as on the host.

**Container:-------------------------------------------------------------------------------------**
There is no content in /proc/....

lxc@homebridgedev:~$ cat /proc/cpuinfo
[..]
Hardware        : BCM2711
Revision        : b03114
Serial          : 1000000045c2ebe1
Model           : Raspberry Pi 4 Model B Rev 1.4

lxc@homebridgedev:~$ cat /proc/1/sched
systemd (1, #threads: 1)
-------------------------------------------------------------------
se.exec_start                                :       9096519.620594
se.vruntime                                  :        174657.350751
se.sum_exec_runtime                          :           609.064479
se.nr_migrations                             :                   23
nr_switches                                  :                  923
nr_voluntary_switches                        :                  501
nr_involuntary_switches                      :                  422
se.load.weight                               :                 1024
se.avg.load_sum                              :                  186
se.avg.runnable_sum                          :               190464
se.avg.util_sum                              :               167936
se.avg.load_avg                              :                    0
se.avg.runnable_avg                          :                    0
se.avg.util_avg                              :                    0
se.avg.last_update_time                      :        9096382654464
se.avg.util_est.ewma                         :                    8
se.avg.util_est.enqueued                     :                    0
policy                                       :                    0
prio                                         :                  120
clock-delta                                  :                  148

**Remote (Host):----------------------------------------------------------------------------------**
pi@raspberrydev:~ $ cat /proc/cpuinfo
[..]
Hardware        : BCM2711
Revision        : b03114
Serial          : 1000000045c2ebe1
Model           : Raspberry Pi 4 Model B Rev 1.4

pi@raspberrydev:~ $ cat /proc/1/sched
systemd (1, #threads: 1)
-------------------------------------------------------------------
se.exec_start                                :       8756515.233873
se.vruntime                                  :          1652.941173
se.sum_exec_runtime                          :          5314.364120
se.nr_migrations                             :                   52
nr_switches                                  :                 2339
nr_voluntary_switches                        :                 1122
nr_involuntary_switches                      :                 1217
se.load.weight                               :                 1024
se.avg.load_sum                              :                  480
se.avg.runnable_sum                          :               491520
se.avg.util_sum                              :               470016
se.avg.load_avg                              :                    0
se.avg.runnable_avg                          :                    0
se.avg.util_avg                              :                    0
se.avg.last_update_time                      :        8756336242688
se.avg.util_est.ewma                         :                   10
se.avg.util_est.enqueued                     :                    0
policy                                       :                    0
prio                                         :                  120
clock-delta                                  :                  112

**Comment by ebaauw** [comment]
Damn, that doesn’t give any clue.  From what I can find on stackexchange, there seems to be no generic, reliable way to determine whether you’re running in a container.  I need to check if I can use the presence of `vcgencmd` to conclude I’m running in a container.  Otherwise, I’ll probable need to add a config.json key `forceRemote` to the `host` section.

**Comment by ebaauw** [comment]
Can you try beta v1.3.3-0?  That should check whether `vcgencmd` can be run, before concluding the specified host is the localhost.

**Comment by uli-rpi** [comment]
I tried the v1.3.3.-0 beta, 

it works for me,
getting the following log without any errors from vcgencmd 
[24.5.2021, 11:21:52] [RPi] RPI-DEV Remote: set Current Temperature from 36°C to 36.5°C
[24.5.2021, 11:21:52] [RPi] RPI-DEV Remote: set Frequency from 900MHz to 1000MHz
[24.5.2021, 11:21:52] [RPi] RPI-DEV Remote: set Load from 0.09 to 0.14
[24.5.2021, 11:22:07] [RPi] RPI-DEV Remote: set Current Temperature from 36.5°C to 36°C
[24.5.2021, 11:22:07] [RPi] RPI-DEV Remote: set Frequency from 1000MHz to 1500MHz
[24.5.2021, 11:22:07] [RPi] RPI-DEV Remote: set Load from 0.14 to 0.11
[24.5.2021, 11:22:22] [RPi] RPI-DEV Remote: set Current Temperature from 36°C to 37°C
[24.5.2021, 11:22:22] [RPi] RPI-DEV Remote: set Frequency from 1500MHz to 700MHz
[24.5.2021, 11:22:22] [RPi] RPI-DEV Remote: set Load from 0.11 to 0.09
[24.5.2021, 11:22:23] [RPi] RPI-DEV Remote Power LED: On changed from true to false
[24.5.2021, 11:22:25] [RPi] RPI-DEV Remote Power LED: On changed from false to true
[24.5.2021, 11:22:37] [RPi] RPI-DEV Remote: set Load from 0.09 to 0.22
[24.5.2021, 11:22:51] [RPi] RPI-DEV Remote: set Current Temperature from 37°C to 37.4°C
[24.5.2021, 11:22:51] [RPi] RPI-DEV Remote: set Frequency from 700MHz to 1500MHz
[24.5.2021, 11:22:51] [RPi] RPI-DEV Remote: set Load from 0.22 to 0.25
[24.5.2021, 11:23:07] [RPi] RPI-DEV Remote: set Current Temperature from 37.4°C to 37°C
[24.5.2021, 11:23:07] [RPi] RPI-DEV Remote: set Frequency from 1500MHz to 800MHz
[24.5.2021, 11:23:07] [RPi] RPI-DEV Remote: set Load from 0.25 to 0.2

The temperature and the power led are displayed in the accessories.

**Comment by ebaauw** [comment]
Released v1.3.3.
